const fs = require('fs');
const child = require('child_process');

const html = fs.readFileSync('money-mission-tracker-v2_5.html', 'utf8');
const failures = [];
let checks = 0;
const expect = (condition, label) => { checks += 1; if (!condition) failures.push(label); };

const recognizerSource = html.match(/function missionT64JeanContentPlannerRequestV25\(text\)\{[^\n]+\}/);
expect(recognizerSource, 'deterministic recognizer exists');
if (recognizerSource) {
  const recognizes = Function(`${recognizerSource[0]}; return missionT64JeanContentPlannerRequestV25;`)();
  expect(recognizes('Create a content plan for A1XX'), 'supported content-plan request stages');
  expect(recognizes('Draft our YouTube plan'), 'supported YouTube-plan request stages');
  expect(!recognizes('Create a sales plan for A1XX'), 'unsupported job stays inert');
  expect(!recognizes('Tell me about content planning'), 'read-only question stays inert');
  expect(!recognizes('Create a content plan for Acme Corp'), 'unsupported external target stays inert');
}

const prepare = html.match(/function prepareMissionT64JeanContentPlannerPreviewV25[\s\S]*?\n\}/);
const preview = html.match(/function openMissionT64JeanContentPlannerPreviewV25[\s\S]*?\n\}/);
const ask = html.match(/askMissionCommand=function\(\)\{[^\n]+\};/);
expect(prepare && /captain:'Jean'/.test(prepare[0]), 'Jean maps to Captain');
expect(prepare && /job:'Content Planner'/.test(prepare[0]), 'Content Planner maps to Job');
expect(prepare && /stage_state:'ready'/.test(prepare[0]), 'primary state is ready');
expect(prepare && /internal_substate:'review_prepared'/.test(prepare[0]), 'initial internal substate is review prepared');
expect(prepare && /workers:\[\],tools:\[\]/.test(prepare[0]), 'Workers and tools are empty');
expect(prepare && /title:'Prepare a Content Plan for Executive Review'/.test(prepare[0]), 'approved work title includes the exact article');
expect(prepare && /owner:'Jean · Content Captain'/.test(prepare[0]), 'owner metadata is Jean Content Captain');
expect(/Chief of Staff made routing recommendation/.test(html), 'Chief remains the recommendation author');
expect(/I prepared the Content Plan handoff from the Chief of Staff’s recommendation and sent it to Agent Inbox for your review\./.test(html), 'Executive Assistant chat announces initial pre-confirm delivery');
expect(ask && /prepareMissionT64JeanContentPlannerPreviewV25\(q\)/.test(ask[0]) && !/openMissionT64JeanContentPlannerPreviewV25\(q\)/.test(ask[0]), 'Enter prepares without opening modal');
expect(ask && />Review handoff<\/button>/.test(ask[0]) && /type="button"/.test(ask[0]), 'reply has accessible Review handoff button');
expect(prepare && !/openMissionPhase1ModalV25|MISSION_PHASE1_INBOX_V25|confirmMissionAssignmentV25/.test(prepare[0]), 'preparation does not open, confirm, or create Inbox activity');
expect(preview && /openMissionT620CurrentHandoffV25/.test(preview[0]), 'Review handoff click resolves current handoff in existing modal');
expect(/item\.stage_state='parked'/.test(html), 'Park is memory-only state');
expect(/item\.stage_state='ready';item\.internal_substate='awaiting_start_approval'/.test(html), 'confirmed Jean preview remains production ready and awaits start approval');
expect(/function missionT64DecisionFeedbackV25/.test(html) && /mcShowToastV10/.test(html), 'Park and Confirm use existing toast feedback');
expect(/Handoff parked locally/.test(html) && /Submit the request again/.test(html), 'Park adds truthful EA bubble with next action');
expect(/Handoff ready for Jean/.test(html) && />Open Agent Inbox<\/button>/.test(html), 'Confirm adds truthful EA readiness bubble with accessible Inbox control');
expect(/missionT620CreateInitialDeliveryV25\(item\)/.test(prepare && prepare[0]) && /missionT626DeliverMessageV25\(item,message\)/.test(html), 'initial Jean handoff enters Inbox as its own unread delivery before confirmation');
expect(/if\(assignment\.contract==='t6_4_jean_content_planner_local_preview'\)\{item\.unread=false;renderMissionAgentInboxV25\(\)/.test(html), 'Review acknowledges the specific Jean item');
expect(/<dt>Project<\/dt>.*<dt>Captain<\/dt>.*<dt>Job<\/dt>.*<dt>Skills<\/dt>.*<dt>Workers<\/dt>.*<dt>Tools<\/dt>.*<dt>State<\/dt>/.test(html), 'Inbox Review shows full Jean handoff contract');
expect(/Jean is not dispatched/.test(html) && /separately approved execution decision/.test(html), 'Inbox detail preserves no-dispatch next step');
expect(/item\.feedbackShown===action/.test(html), 'repeat decision feedback is deduplicated');
const park = html.match(/function parkMissionT64JeanContentPlannerPreviewV25\([^)]*\)\{[^\n]+\}/);
expect(park && park[0].indexOf('closeMissionPhase1ModalV25()') < park[0].indexOf("missionT64DecisionFeedbackV25(item,'parked')"), 'Park closes modal before toast and EA bubble');
const confirm = html.match(/function confirmMissionAssignmentV25\([^)]*\)\{[^\n]+\}/);
expect(confirm && confirm[0].indexOf('closeMissionPhase1ModalV25()') < confirm[0].indexOf("missionT64DecisionFeedbackV25(item,'confirmed')"), 'Confirm still closes modal before feedback');

const addedSurface = [prepare && prepare[0], preview && preview[0], recognizerSource && recognizerSource[0], ask && ask[0]].join('\n');
expect(!/fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage\.setItem|sessionStorage\.setItem|indexedDB|new Worker\s*\(|dispatchAgent|postToAppsScript|Today|Agency Feed|receipt/i.test(addedSurface), 'preview has zero external/runtime/persistence/promotion effects');
expect(!/data-tab=|<nav|relationship map|output card/i.test(addedSurface), 'preview adds no nav, relationship map, or output surface');

const t67Start = html.indexOf('function missionT67HandoffReviewStepsMarkupV25');
const t67End = html.indexOf('function prepareMissionT64JeanContentPlannerPreviewV25');
const t67 = html.slice(t67Start, t67End);
expect(t67Start > -1 && t67End > t67Start, 'T6.7 helpers are adjacent to T6.4');
['Mission Command', 'Chief of Staff made routing recommendation', 'Executive Assistant prepared review', '@A1XX decision', 'What needs me', 'CURRENT', 'NEXT', 'LATER', 'Safe destination', 'Additional details', 'Full original command'].forEach((token) => expect(t67.includes(token), `approved hierarchy includes ${token}`));
['A1XX', 'Chief of Staff', 'Jean', 'Content Planner', 'Content Plan'].forEach((token) => expect(t67.includes(token), `visual route includes ${token}`));
['What happened', 'What now', 'What needs me', 'What this action does', 'What next'].forEach((token) => expect(t67.includes(token), `five-question readback includes ${token}`));
expect(/mode==='inbox'\?\[\['DONE','Routing confirmed',false\],\['CURRENT · NOT CONNECTED','Agent Inbox Review',true\]/.test(t67), 'Inbox Review has state-specific stepper');
expect(/data-handoff-review-state="'\+\(inbox\?'inbox':'review'\)/.test(t67), 'only review and inbox modal states render');
expect(!/data-handoff-review-state[^\n]*(confirmed|parked)/.test(t67), 'no persistent Confirmed or Parked modal states');
expect(/aria-current="step"/.test(t67) && /aria-live="polite"/.test(t67), 'stepper and readback expose state accessibly');
expect(/id="mc-t67-revision-note" aria-invalid="false" aria-describedby="mc-t67-revision-error"/.test(t67), 'revision note has accessible validation contract');
expect(/A revision note is required/.test(t67) && /input\.focus\(\{preventScroll:true\}\)/.test(t67), 'empty revision is rejected and focused');
expect(/item\.revision_note=note/.test(t67) && /nothing was staged or dispatched/.test(t67), 'valid revision stays local and truthful');
expect(/missionPhase1EscapeV25\(item\.project\)/.test(t67) && /missionPhase1EscapeV25\(\(item\.skills\|\|\[\]\)\.join/.test(t67) && /missionPhase1EscapeV25\(item\.revision_note\|\|''\)/.test(t67), 'dynamic handoff facts are escaped');
expect(/0 calls · 0 runs · 0 writes/.test(t67) && /not dispatched/.test(t67), 'zero-effect truth is visible');
expect(t67.includes('No output exists yet. A future returned result would link to one canonical Output visible through Inbox, Library, and Agents &gt; Outputs.'), 'Inbox Review states the full no-output and canonical-location contract');
expect(!/fetch\s*\(|XMLHttpRequest|WebSocket|google\.script\.run|localStorage\.setItem|sessionStorage\.setItem|indexedDB|new Worker\s*\(|postToAppsScript|dispatchAgent|deliverySend|receipt/i.test(t67), 'T6.7 helpers contain no forbidden capability');

const cssStart = html.indexOf('#mc-phase1-modal-scoped .mc-handoff-review-shell');
const cssEnd = html.indexOf('@media(max-width:1000px)', cssStart);
const t67Css = html.slice(cssStart, cssEnd);
expect(cssStart > -1 && cssEnd > cssStart, 'T6.7 scoped CSS exists');
expect(!/(^|[},])\s*\.mc-handoff-review-/m.test(t67Css), 'every Handoff Review selector is host-scoped');
['@media(max-width:760px)', '@media(max-width:520px)', '@media(prefers-reduced-motion:reduce)', 'overflow-wrap:anywhere', 'min-width:0'].forEach((token) => expect(t67Css.includes(token), `responsive CSS includes ${token}`));
expect(/\.mc-handoff-review-hero\{text-align:left/.test(t67Css) && /\.mc-handoff-review-movement\{[^}]*justify-content:flex-start/.test(t67Css), 'EA letter and compact movement are left aligned');
expect(/\.mc-handoff-review-control:hover \.mc-handoff-review-tip/.test(t67Css) && /\.mc-handoff-review-control:focus-within \.mc-handoff-review-tip/.test(t67Css), 'hidden help appears only on hover or keyboard focus-within');
expect(!/data-open|mc-handoff-review-help/.test(t67Css), 'CSS has no sticky help selector or visible help button');
expect(/\.mc-handoff-review-visible-routing \.mc-handoff-review-stepper\{margin-top:22px;gap:12px\}/.test(t67Css), 'desktop stepper has increased route separation and internal spacing');
expect(/\.mc-handoff-review-visible-routing \.mc-handoff-review-step small\{font-size:8px\}/.test(t67Css) && /\.mc-handoff-review-visible-routing \.mc-handoff-review-step b\{font-size:11px/.test(t67Css), 'stepper tags and targets are modestly larger');
expect(/@media\(max-width:760px\)[\s\S]*\.mc-handoff-review-visible-routing \.mc-handoff-review-stepper\{margin-top:16px;gap:6px\}/.test(t67Css), 'mobile stepper spacing remains proportional');
expect(/#mc-phase1-modal-scoped \.mc-handoff-review-details \.mc-handoff-review-groups\+\.mc-handoff-review-label\{display:block;margin-top:12px\}/.test(html), 'Full original command label has modest scoped separation from preceding details');
expect(/#mc-phase1-modal-scoped \.mc-handoff-review-letter\{[^}]*text-align:left/.test(html) && /\.mc-handoff-review-letter p\+p\{margin-top:7px\}/.test(html), 'EA letter is locally scoped, left aligned, and separates sentences modestly');
expect(/#mc-phase1-modal-scoped \.mc-handoff-review-signoff\{[^}]*text-align:left[^}]*font-size:10px/.test(html), 'EA sign-off uses restrained scoped message-close styling');
expect(/id="mc-phase1-modal-scoped"/.test(html), 'existing modal host carries the scope id');

const staged = html.match(/function openMissionStagedAssignmentV25\(id\)\{[^\n]+\}/);
expect(staged && /if\(assignment\.contract==='t6_4_jean_content_planner_local_preview'\)/.test(staged[0]), 'full Inbox hierarchy is contract-linked only');
expect(staged && /openMissionPhase1ModalV25\('Ready for Handoff',item\.title,'This assignment is staged locally\. No dispatch occurred\.'/.test(staged[0]), 'generic staged fallback is preserved');
expect(/if\(!MISSION_STAGE4_MASTER_ENABLED_V25\|\|!MISSION_STAGE4_BROWSER_V25\.enabled\)/.test(html), 'Stage4 default-off wrapper is preserved');
expect(/if\(modal&&modal\.classList\.contains\('open'\)\)\{event\.preventDefault\(\);closeMissionPhase1ModalV25\(\)/.test(html), 'Escape still closes modal through existing focus-return path');

const inboxRenderer = html.match(/function renderMissionAgentInboxV25\(\)\{[\s\S]*?\n\}/);
expect(inboxRenderer && /assignment\.contract==='t6_4_jean_content_planner_local_preview'/.test(inboxRenderer[0]), 'Inbox naming branch is contract-specific');
expect(inboxRenderer && /var message=missionT616MessageV25\(item\);return '<article[^\n]+<strong>'\+missionPhase1EscapeV25\(message\.subject\)/.test(inboxRenderer[0]), 'contract Inbox row leads with the EA message subject');
expect(inboxRenderer && /mc-agent-inbox-meta"><span>From: Executive Assistant<\/span><span>1 attachment<\/span><\/div>/.test(inboxRenderer[0]), 'contract row metadata is exactly EA sender and one attachment');
expect(inboxRenderer && !/Underlying author: Chief of Staff/.test(inboxRenderer[0]), 'contract list row omits Chief provenance metadata');
expect(inboxRenderer && /item\.source\+' · '\+\(item\.title\|\|item\.label\)/.test(inboxRenderer[0]), 'generic legacy source-title output is preserved');
expect(!html.includes('Jean · Jean · Content Planner'), 'redundant Jean title is absent');
expect(!html.includes("title:'Jean · Content Planner'"), 'owner and Job are not used as work title');
expect(/openMissionT620CurrentHandoffV25/.test(html) && /openMissionPhase1ModalV25\(review\?'Handoff Review':'Current Handoff',item\.title/.test(html), 'pre-decision and current Inbox attachment resolve through the work-title modal');
expect(/Your Content Plan handoff is ready for Jean/.test(html) && /Prepare a Content Plan for Executive Review is parked locally/.test(html), 'durable EA decision wording separates confirmed readiness from parked work title');
expect(/Nothing has been confirmed, started, or dispatched\./.test(html), 'initial EA chat separates prepared review from later execution');
expect(/<dt>State<\/dt><dd>Ready for confirmation<\/dd>/.test(t67), 'visible review state is Ready for confirmation');

const provenance = t67.indexOf('Chief of Staff made routing recommendation');
const eaPrepared = t67.indexOf('Executive Assistant prepared review');
const a1xxDecision = t67.indexOf('@A1XX decision');
expect(provenance > -1 && provenance < eaPrepared && eaPrepared < a1xxDecision, 'provenance orders Chief authorship, EA presentation, and A1XX decision');
expect(t67.includes('I reviewed the Chief of Staff’s recommendation and prepared this handoff for you.'), 'EA presents the recommendation conversationally');
expect(t67.includes('Jean</span><i>→</i><span>Draft Content Plan</span><i>→</i><span>@A1XX Review'), 'compact movement is exact');
['Goes to', 'Acting as', 'Expected return', 'Comes back to'].forEach((token) => expect(t67.includes(token), `four-line summary includes ${token}`));
expect(t67.includes('>Confirm Handoff</button>') && t67.includes('>Request Changes</button>') && t67.includes('>Park</button>'), 'approved decision labels are exact');
const decisionStart = t67.indexOf('Approve the Chief of Staff’s routing recommendation?');
expect(decisionStart > -1 && t67.indexOf('>Confirm Handoff</button>', decisionStart) < t67.indexOf('mc-handoff-review-safety', decisionStart), 'permanent no-start line immediately follows decision controls');
['mc-t612-confirm-tip', 'mc-t612-changes-tip', 'mc-t612-park-tip', 'role="tooltip"', 'aria-describedby'].forEach((token) => expect(t67.includes(token), `hidden decision help includes ${token}`));
expect(!/>\?<\/button>|mc-handoff-review-help|missionT612HandoffHelpV25|data-open|aria-expanded/.test(t67), 'no visible or sticky help toggle remains');
const renderedOrder = t67.slice(t67.indexOf("return '<div class=\"mc-handoff-review-shell\""));
const visibleRoute = renderedOrder.indexOf('mc-handoff-review-visible-routing');
const route = renderedOrder.indexOf('missionT67HandoffReviewRouteMarkupV25()', visibleRoute);
const stepper = renderedOrder.indexOf('missionT67HandoffReviewStepsMarkupV25(mode)', visibleRoute);
const details = renderedOrder.indexOf("+details+'</div>'");
expect(visibleRoute > -1 && visibleRoute < route && route < stepper && stepper < details, 'visible route precedes state stepper and closed Additional details');
expect(!t67.includes('<details class="mc-handoff-review-details" open'), 'Additional details is closed by default');
['Formal contract', 'Capabilities', 'Workers', 'Tools', 'Model', 'Effects', 'Source', 'Version', 'No output exists yet'].forEach((token) => expect(t67.includes(token), `deeper details include ${token}`));
expect(/missionPhase1EscapeV25\(item\.request\)/.test(t67), 'full original command is escaped for long-copy safety');

const renderT6121 = Function(`function missionPhase1EscapeV25(value){return String(value == null ? '' : value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}${t67}; return missionT67HandoffReviewBodyV25;`)();
const fixtureItem = { title: 'Prepare a Content Plan for Executive Review', project: 'A1XX', request: '<long command>', skills: ['Audience problem', 'Hook'], revision_note: '' };
const reviewMarkup = renderT6121(fixtureItem, 'review');
const inboxMarkup = renderT6121(fixtureItem, 'inbox');
const scanLabels = ['Workers', 'Tools', 'Model', 'Effects', 'Source', 'Version'];
scanLabels.forEach((label) => {
  const token = `data-scan-row="${label}"`;
  expect(reviewMarkup.split(token).length === 2, `${label} is one distinct semantic scan row`);
});
expect(!/<dt>(Workers|Tools|Model|Effects|Source|Version)<\/dt>/.test(reviewMarkup), 'six scan labels are not grouped into definition-list facts');
expect(!/data-scan-row="(?:Workers · Tools|Model · Effects|Source · Version)"/.test(reviewMarkup), 'six scan labels are never combined');
expect(reviewMarkup.includes('data-scan-row="State"><span>State</span><strong>Ready for confirmation</strong>'), 'pre-decision presentation state is exact');
expect(inboxMarkup.includes('data-scan-row="State"><span>State</span><strong>Handoff confirmed · execution not connected</strong>'), 'Inbox Review presentation state is exact');
expect((reviewMarkup.match(/Formal contract/g) || []).length === 1 && !reviewMarkup.includes('>Routing<'), 'details keep one formal contract and do not duplicate Routing');
expect(reviewMarkup.includes('Full original command') && reviewMarkup.includes('&lt;long command&gt;') && reviewMarkup.includes('No output exists yet'), 'project details preserve escaped command and no-output truth');
const letterSentences = [
  'I reviewed the Chief of Staff’s recommendation and prepared this handoff for you.',
  'The Chief recommends sending it to Jean.',
  'Jean will act as the Content Planner to prepare a Draft Content Plan and return it to you for Executive Review.'
];
expect(reviewMarkup.includes('<div class="mc-handoff-review-letter" aria-label="Executive Assistant recommendation"><p>'), 'pre-decision recommendation uses semantic EA letter markup');
expect(letterSentences.every((sentence) => reviewMarkup.includes(`<p>${sentence}</p>`)), 'each exact EA recommendation sentence has its own block');
const letterOne = reviewMarkup.indexOf(letterSentences[0]);
const letterTwo = reviewMarkup.indexOf(letterSentences[1]);
const letterThree = reviewMarkup.indexOf(letterSentences[2]);
const controlsEnd = reviewMarkup.indexOf('Nothing will start from this decision.');
const signature = reviewMarkup.indexOf('— Your Executive Assistant');
const signatureSource = reviewMarkup.indexOf('Prepared from the Chief of Staff’s recommendation.');
const lowerRoute = reviewMarkup.indexOf('mc-handoff-review-visible-routing');
expect(letterOne < letterTwo && letterTwo < letterThree && letterThree < controlsEnd && controlsEnd < signature && signature < signatureSource && signatureSource < lowerRoute, 'letter, controls, safety, EA sign-off, and lower route render in exact order');
expect((reviewMarkup.match(/— Your Executive Assistant/g) || []).length === 1 && !inboxMarkup.includes('— Your Executive Assistant') && !inboxMarkup.includes('mc-handoff-review-letter'), 'EA sign-off and letter appear only in pre-decision review');
expect(!/Executive Assistant (recommended|approved|dispatched|executed)/i.test(reviewMarkup), 'sign-off does not transfer Chief authorship or claim approval or execution');

const t616Start = html.indexOf('var MISSION_T616_ZERO_EFFECTS_V25');
const t616End = html.indexOf('function missionPhase1UnifiedInboxV25', t616Start);
const t616 = html.slice(t616Start, t616End);
expect(t616Start > -1 && t616End > t616Start, 'T6.16 contract-local fixture helpers exist adjacent to base Inbox');
['message_id', 'conversation_id', 'source_inbox_message_id', 'attachment_ids', 'project_id', 'handoff_id', 'output_id', 'safe_summary', 'default_voice'].forEach((token) => expect(t616.includes(token), `safe fixture contract includes ${token}`));
expect(/attachment_ids:\['att_'\+latest\.message_id\.slice\(4\)\]/.test(t616) && /attachment_id:message\.attachment_ids\[0\]/.test(t616), 'each selected message owns exactly one message-specific typed attachment');
expect(/1 attachment/.test(t616) && /📎/.test(t616) && /Confirmed Content Plan Handoff/.test(t616), 'Inbox detail presents one visible confirmed handoff attachment');
expect(/From · Executive Assistant/.test(t616) && /Underlying author · Chief of Staff/.test(t616), 'EA presenter and Chief author remain distinct');
expect(/You confirmed the Chief of Staff’s recommendation\./.test(t616) && /— Your Executive Assistant/.test(t616), 'Inbox owns the confirmed EA sentence letter and exact sign-off');
expect(/Ready for Jean · waiting for approval to start/.test(t616) && /Jean has not started/.test(t616), 'message state and no-start truth are visible');
expect(/Reply in Mission Command/.test(t616) && /Open original Inbox message/.test(t616) && /Continue conversation/.test(t616), 'two-way Mission Command controls are present');
expect(/closeMissionAgentInboxV25\(false\);return openMissionT620CurrentHandoffV25\(item\.assignment\.handoff_id,launcher,true\)/.test(t616), 'paperclip closes Inbox before resolving current handoff with narrow return');
expect(/openMissionT620CurrentHandoffV25/.test(t616), 'paperclip reuses the current full Handoff V1 resolver');
expect(/missionT616RestoreInboxMessageV25\('mc-t616-attachment'\)/.test(t616), 'modal close returns to the same attachment control');
expect(/MISSION_T616_INBOX_VIEW_V25\.scrollTop/.test(t616) && /list\.scrollTop=MISSION_T616_INBOX_VIEW_V25\.scrollTop/.test(t616), 'Inbox message scroll position is restored');
expect(/MISSION_T616_CONVERSATIONS_V25\[message\.source_inbox_message_id\]/.test(t616) && /if\(prior\)return \{ok:true,created:false/.test(t616), 'contextual EA conversation is page-memory and idempotent by source message');
expect(/prior&&prior\.fingerprint!==fingerprint/.test(t616) && /conflict:true/.test(t616), 'changed safe inputs produce an explicit fingerprint conflict');
expect(/Object\.freeze\(\{workspace:'Mission Command'/.test(t616) && /captain_thread:false,permanent_agent_thread:false/.test(t616), 'safe context envelope is closed and not a Captain or permanent thread');
expect(/setMissionCommandModeV25\('chat'\)/.test(t616) && /document\.getElementById\('mission-command-thread'\)/.test(t616), 'Reply reuses the existing Mission Command card and thread');
expect(/var company=document\.getElementById\('company-panel'\);if\(company&&!company\.classList\.contains\('open'\)&&typeof toggleCompanyPanel==='function'\)toggleCompanyPanel\(\)/.test(t616), 'local reply reveals Mission Command only when the existing card is closed');
try {
  const replySource = t616.match(/function replyMissionT616InMissionCommandV25\(id\)\{[^\n]+\}/)[0];
  const probe = `'use strict';const assert=require('assert');${replySource};function run(open){let toggles=0,focuses=0;const panel={classList:{contains(){return open;}}},thread={innerHTML:'prior',scrollTop:0,scrollHeight:4},input={value:'prior',placeholder:'prior',readOnly:false,focus(){focuses++;}};global.document={getElementById(id){return id==='company-panel'?panel:id==='mission-command-thread'?thread:input;}};global.toggleCompanyPanel=()=>{toggles++;};global.missionT616ContractItemV25=()=>({id:'msg'});global.missionT616OpenConversationV25=()=>({ok:true,envelope:{source_inbox_message_id:'msg_source',safe_summary:'Safe'}});global.MISSION_T616_INBOX_VIEW_V25={selectedMessageId:''};global.closeMissionAgentInboxV25=()=>{};global.setMissionCommandModeV25=()=>{};global.MISSION_T616_CHAT_VIEW_V25={active:false,sourceMessageId:'',priorThreadHtml:'',priorThreadScroll:0,priorInputValue:'',priorInputPlaceholder:'',priorInputReadOnly:false};global.missionPhase1EscapeV25=v=>v;const result=replyMissionT616InMissionCommandV25('msg');return {result,toggles,focuses,readOnly:input.readOnly};}const closed=run(false),opened=run(true);assert.equal(closed.result.ok,true);assert.equal(closed.toggles,1);assert.equal(closed.focuses,1);assert.equal(closed.readOnly,true);assert.equal(opened.result.ok,true);assert.equal(opened.toggles,0);assert.equal(opened.focuses,1);assert.equal(opened.readOnly,true);`;
  child.execFileSync(process.execPath, ['-e', probe], {stdio:'pipe'});
  expect(true, 'executable reply regression opens a closed card and preserves an already-open card');
} catch (error) {
  expect(false, 'executable reply regression opens a closed card and preserves an already-open card');
}
expect(!/startMissionNewChat|setActiveMissionSession|saveMissionChat|saveMissionChatSession|postMissionChatLog|_askMissionCommandPhase1BaseV25|fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage|sessionStorage|indexedDB|WebSocket|new Worker|dispatchAgent|emitAudit|auditEvent|activityLedger/i.test(t616), 'T6.16 fixture avoids persistent chat, provider, network, worker, dispatch, and audit paths');
expect(/input\.readOnly=true/.test(t616) && /MISSION_T616_CHAT_VIEW_V25\.active\)\{continueMissionT616ConversationV25\(\)/.test(html), 'contextual fixture cannot fall through to the normal send path');
expect(/item\.unread=false;renderMissionAgentInboxV25\(\)/.test(t616), 'opening message acknowledges unread without another effect');
expect(/subject:'Your Content Plan handoff is ready for Jean'/.test(t616), 'confirmed EA message subject is exact');
expect(/<h3 id="mc-t616-message-heading" tabindex="-1">'\+missionPhase1EscapeV25\(message\.subject\)/.test(t616), 'message detail heading uses the same subject field');
expect(/missionPhase1EscapeV25\(message\.subject\)/.test(inboxRenderer && inboxRenderer[0]), 'contract Inbox row uses the message subject instead of the assignment title');
expect(/title:'Prepare a Content Plan for Executive Review'/.test(prepare && prepare[0]) && /title:'Confirmed Content Plan Handoff'/.test(t616), 'formal assignment and confirmed attachment titles remain exact and separate');
expect(/aria-live="polite"/.test(t616) && /aria-label="Open '\+missionPhase1EscapeV25\(message\.attachment_title\)\+' attachment"/.test(t616), 'message detail exposes live state and a handoff-specific accessible attachment name');
['You confirmed the Chief of Staff’s recommendation.', 'The handoff is now ready for Jean to take on as Content Planner.', 'Jean has not started. The next step is your approval to begin work.'].forEach((sentence) => expect(t616.includes(sentence), `confirmed EA message data includes ${sentence}`));
expect(/No start action is connected yet/.test(t616) && /Handoff confirmed · execution not connected/.test(t67), 'confirmed Inbox and full Handoff Review both explain execution is not connected');
expect(!/(handoff was sent|Jean was sent|Jean has started|Jean was dispatched|was added to Agent Inbox)/i.test(t616), 'confirmed message makes no premature sent, started, dispatched, or Inbox-addition claim');
expect(!/added to Agent Inbox/i.test(html) && /confirmed handoff will be ready for Jean pending separate execution approval/.test(html), 'all contract copy describes readiness instead of Inbox addition');
expect(/class="mc-t616-detail" aria-live="polite" aria-current="true"/.test(t616), 'only the selected message detail exposes aria-current');
expect(/missionT616ModalReturnV25=null/.test(html) && /if\(afterClose\)\{afterClose\(\);return;\}/.test(html), 'shared modal consumes the contract return callback exactly once');
expect(/function closeMissionT616InboxMessageV25\(\)\{var originId=MISSION_T616_INBOX_VIEW_V25\.originId/.test(t616), 'Back captures the selected row focus token before rerender');
expect(/setTimeout\(function\(\)\{var origin=originId&&document\.getElementById\(originId\)\|\|document\.getElementById\('mc-agent-inbox-close'\);if\(origin\)origin\.focus\(\{preventScroll:true\}\)/.test(t616), 'Back restores the saved row after rerender without scrolling and falls back to Inbox close');
expect(/if\(MISSION_T616_INBOX_VIEW_V25\.originId===originId\)MISSION_T616_INBOX_VIEW_V25\.originId='';/.test(t616), 'row focus token is consumed only when it still matches');
expect(/MISSION_T616_INBOX_VIEW_V25\.outerLauncher=missionPhase1LastFocusV25/.test(t616), 'opening contract detail captures the ordinary outer Inbox launcher');
expect(/var outer=MISSION_T616_INBOX_VIEW_V25\.outerLauncher\|\|missionPhase1LastFocusV25;openMissionAgentInboxV25\(\);missionPhase1LastFocusV25=outer/.test(t616), 'contract reopen restores the outer launcher after ordinary popup open');
expect(/missionT616RestoreInboxMessageV25\('mc-t616-attachment'\)/.test(t616) && /missionT616RestoreInboxMessageV25\('mc-t616-message-heading'\)/.test(t616), 'attachment close and Open original return to deterministic controls');
expect(/function closeMissionAgentInboxV25\(returnFocus\)[^\n]+missionPhase1LastFocusV25\.focus/.test(html), 'Inbox X and Escape retain the generic outer-launcher focus path');

const t616CssStart = html.indexOf('.mc-agent-inbox .mc-t616-detail');
const t616CssEnd = html.indexOf('.mc-phase1-modal-backdrop', t616CssStart);
const t616Css = html.slice(t616CssStart, t616CssEnd);
expect(t616CssStart > -1 && t616CssEnd > t616CssStart, 'T6.16 CSS is scoped to the existing Inbox host');
expect(!/(^|[},])\s*\.mc-t616-/m.test(t616Css), 'every T6.16 selector is Inbox-host scoped');
['overflow-wrap:anywhere', 'min-width:0', '@media(max-width:760px),(min-resolution:1.45dppx)', '@media(prefers-reduced-motion:reduce)', 'flex-wrap:wrap'].forEach((token) => expect(t616Css.includes(token), `T6.16 responsive CSS includes ${token}`));
expect(/button:focus-visible/.test(t616Css) && /outline:2px solid/.test(t616Css), 'T6.16 controls retain visible keyboard focus');
expect(/\.mc-t626-message-nav button,.mc-agent-inbox \.mc-t616-actions button\{appearance:none;border:0;border-bottom:1px/.test(t616Css), 'message navigation and actions use low-chrome text-link controls');
expect(!/\.mc-t616-actions button:first-child/.test(t616Css) && !/\.mc-t616-actions button\{width:100%/.test(t616Css), 'message footer does not restore bulky full-width action buttons');

const t620Start = html.indexOf('var MISSION_T620_HANDOFFS_V25');
const t620End = html.indexOf('function missionT616ContractItemV25', t620Start);
const t620 = html.slice(t620Start, t620End);
expect(t620Start > -1 && t620End > t620Start, 'T6.21 canonical handoff registry is adjacent to the contract branch');
expect(/MISSION_T620_HANDOFFS_V25=\{\}/.test(t620) && /MISSION_T620_ACTIONS_V25=\{\}/.test(t620), 'handoffs and actions use isolated page-memory registries');
expect(/handoff_id:'hof_content-plan-'\+stamp/.test(html) && /handoff_version:1/.test(html) && /lifecycle_state:'review_prepared'/.test(html), 'preparation allocates one stable versioned handoff');
expect(/missionT620CreateInitialDeliveryV25\(item\)/.test(html), 'initial Inbox delivery occurs while review is prepared');
expect(/I prepared a Content Plan handoff for your review/.test(t620) && /Content Plan Handoff Review/.test(t620), 'initial message and attachment describe pre-confirm review truth');
expect(/Ready for your routing decision/.test(t620) && /unread:unread!==false/.test(t620), 'initial delivery is unread and waiting for the routing decision');
expect(/missionT620CurrentLinkV25/.test(t620) && /openMissionT620CurrentHandoffV25/.test(t620), 'current links resolve the latest state of the stable handoff');
expect(/missionT620HistoricalLinkV25/.test(t620) && /Historical Handoff · Read Only/.test(t620) && /HISTORICAL VERSION · READ ONLY/.test(t620), 'historical version links render an explicitly read-only snapshot');
expect(/View Version/.test(html) && /openMissionT620HistoricalHandoffV25/.test(html), 'current Handoff Review exposes its historical version link in Additional details');
expect(/View current handoff/.test(t620), 'historical view provides a safe path to the latest handoff state');
expect(/handoff\.lifecycle_state!==expectedState\|\|handoff\.handoff_version!==expectedVersion/.test(t620), 'decision guard checks expected state and version');
expect(/stale_action_conflict/.test(t620) && /duplicate_action_conflict/.test(t620), 'stale tabs and conflicting duplicate actions fail closed');
expect(/prior\.result==='stale'/.test(t620), 'reopening a previously rejected stale action remains rejected');
expect(/created:false/.test(t620) && /result:'applied'/.test(t620), 'identical applied action replay is idempotent');
expect(/missionT626DeliverMessageV25\(item,confirmed\)/.test(html) && /MISSION_PHASE1_INBOX_V25\.unshift\(row\)/.test(t620), 'Confirm delivers a separate immutable message row');
expect(/missionT626RowForMessageV25\(item\.handoff_id,message\.message_id\)/.test(t620) && /if\(existing\)return \{created:false,row:existing\}/.test(t620), 'duplicate delivery protection is keyed by stable handoff and exact message');
expect(/handoff\.messages\.push\(missionT620ConfirmedMessageV25/.test(t620), 'Confirm appends the immutable confirmed delivery to the same handoff');
expect(/id:'inbox_'\+message\.message_id/.test(t620) && /message_id:message\.message_id,handoff_id:item\.handoff_id/.test(t620), 'Inbox rows have distinct IDs while sharing one stable handoff');
expect(/function missionT626ExactMessageV25/.test(t616) && /message\.message_id===item\.message_id/.test(t616), 'row and detail resolve the exact immutable source message');
expect(/Message '\+\(position\+1\)\+' of '\+messages\.length/.test(t616), 'detail identifies the selected message position');
expect(/openMissionT626AdjacentMessageV25/.test(t616) && t616.includes('>Previous</button>') && t616.includes('>Next</button>'), 'detail provides bounded Previous and Next message navigation');
expect(/>Current handoff<\/button>/.test(t616) && />Attached Version '\+message\.handoff_version\+'<\/button>/.test(t616) && /openMissionT626AttachedVersionV25/.test(t616), 'detail separates latest-state resolution from its attached read-only version');
expect(/mc-t626-message-tools/.test(t616) && /mc-t626-message-nav/.test(t616) && /aria-label="Message actions"/.test(t616), 'message navigation and actions form a restrained semantic footer');
expect(/row\.unread=false/.test(t616) && /item\.unread=false/.test(t616), 'opening or navigating acknowledges only the selected message row');
expect(/source_inbox_message_id:latest\.message_id/.test(t616) && /MISSION_T616_CONVERSATIONS_V25\[message\.source_inbox_message_id\]/.test(t616), 'Reply context remains bound to the exact source message');
expect(/if\(confirmed\)missionT626DeliverMessageV25\(item,confirmed\)/.test(html) && !/existing\.unread=true;existing\.state='waiting'/.test(html), 'confirmation never mutates the initial message into the confirmed message');
expect(/Legacy local handoff · earlier history unavailable/.test(html) && /Earlier actors, approvals, timestamps, messages, and versions are unavailable/.test(html), 'pre-registry T6.16 records are labeled as legacy without invented history');
expect(/missionPhase1AssignmentV25=item/.test(t620), 'old current links restore the resolved handoff as modal context');
expect(/writes:0,storage_calls:0,network_calls:0/.test(t620) && !/(fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage|sessionStorage|indexedDB|WebSocket|new Worker|emitAudit|auditEvent)/i.test(t620), 'T6.21 registry and resolver remain exact-zero and capability-free');

expect(/function missionT623TabbedBodyV25/.test(t620), 'T6.23 tabbed handoff composition is contract-local');
expect(/role="tablist" aria-label="Handoff views"/.test(t620), 'Handoff exposes one semantic tablist');
['Review', 'Journey', 'History'].forEach((label) => expect(new RegExp('>'+label+'<\\/button>').test(t620), `T6.23 ${label} tab exists`));
expect(['review-panel','journey-panel','history-panel'].every((token) => t620.includes(token)), 'T6.23 renders the three named tab panels');
expect(/aria-selected="true"[^>]+>Review/.test(t620) && /data-view="journey"[^>]+hidden/.test(t620) && /data-view="history"[^>]+hidden/.test(t620), 'Review is default and secondary panels start hidden');
expect(/function missionT623OpenTabV25/.test(t620) && /\['review','journey','history'\]\.indexOf\(view\)<0/.test(t620), 'tab navigation rejects unknown views');
expect(/panel\.hidden=panel\.getAttribute\('data-view'\)!==view/.test(t620) && /target\.focus\(\{preventScroll:true\}\)/.test(t620), 'tab navigation changes presentation and transfers focus');
expect(/System-controlled roadmap/.test(t620) && /These are not checkboxes/.test(t620), 'Journey is explicitly system-controlled');
expect(/Chief recommendation prepared/.test(t620) && /Handoff delivered to Agent Inbox/.test(t620) && /A1XX confirmed routing/.test(t620), 'Journey contains the completed preparation and routing stages');
expect(/Approve Jean to begin/.test(t620) && /Verify dispatch/.test(t620) && /Draft Content Plan returned/.test(t620) && /Executive Review/.test(t620), 'Journey contains current and later fulfillment stages');
expect(/state==='awaiting_start_approval'\?'current':'later'/.test(t620), 'Journey derives its current start-approval stage from lifecycle state');
expect(/state==='parked'/.test(t620) && /Handoff parked · nothing is running/.test(t620), 'Journey has a truthful parked state');
expect(/local_session_at:new Date\(\)\.toISOString\(\)/.test(t620), 'History records explicit local-session timestamps');
expect(/receipt:'local-session-only'/.test(t620) && /not authenticated or durable production audit records/.test(t620), 'History denies authenticated and durable audit status');
expect(/material_version_created/.test(t620) && /review_prepared/.test(t620) && /inbox_delivered/.test(t620), 'initial history captures material version, preparation, and Inbox delivery');
expect(/routing_confirmed/.test(t620) && /Confirmed routing recommendation/.test(t620), 'Confirm appends a routing history breadcrumb');
expect(/missionT623AppendHistoryV25\(handoff,'parked'/.test(t620), 'Park appends a local history breadcrumb');
expect(/IDs and evidence/.test(t620) && /Effects 0 calls · 0 runs · 0 writes/.test(t620), 'History keeps identifiers and effects behind progressive disclosure');
expect(/body=missionT623TabbedBodyV25\(item,body,handoff\.handoff_version\)/.test(t620), 'current links open the tabbed canonical handoff');
expect(/missionT623TabbedBodyV25\(handoff\.item,missionT620HistoricalBodyV25/.test(t620), 'historical versions keep the same navigation around a read-only Review');
expect(/HISTORICAL VERSION · READ ONLY/.test(t620) && /It cannot be approved, changed, or made current/.test(t620), 'historical Review remains read-only');
expect(!/(fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage|sessionStorage|indexedDB|WebSocket|new Worker|emitAudit|auditEvent)/i.test(t620), 'T6.23 adds no persistence, provider, worker, or audit capability');

const t623CssStart = html.indexOf('#mc-phase1-modal-scoped .mc-t623-tabs-shell');
const t623CssEnd = html.indexOf('@media(max-width:1000px)', t623CssStart);
const t623Css = html.slice(t623CssStart, t623CssEnd);
expect(t623CssStart > -1 && t623CssEnd > t623CssStart, 'T6.23 CSS is confined to the existing modal host');
expect(!/(^|[},])\s*\.mc-t623-/m.test(t623Css), 'every T6.23 selector is host scoped');
expect(/@media\(max-width:760px\)/.test(t623Css) && /grid-template-columns:1fr/.test(t623Css), 'T6.23 stacks Journey and History at narrow widths');
expect(/prefers-reduced-motion:reduce/.test(t623Css) && /focus-visible/.test(t623Css) && /overflow-x:auto/.test(t623Css), 'T6.23 preserves reduced motion, keyboard focus, and tab overflow safeguards');

const t644Start = html.indexOf('/* T6.44 durable-read browser adapter.');
const t644End = html.indexOf('var MISSION_STAGE4_MASTER_ENABLED_V25=false;', t644Start);
const t644 = html.slice(t644Start, t644End);
expect(t644Start > -1 && t644End > t644Start, 'T6.44 adapter is installed before the Stage4 capture boundary');
expect(/MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25=false/.test(t644), 'durable read master flag is literally default-off');
expect(/if\(!MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25\)return \{ok:false,ui_state:'feature_off'/.test(t644), 'feature-off adapter exits before any source read');
expect(/if\(!MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25\|\|!MISSION_T644_CONTROLLER_V25\.adapter\)return _renderMissionAgentInboxT644BaseV25\(\)/.test(t644), 'flag-off Inbox delegates exactly to the released renderer');
expect(/_renderMissionAgentInboxT644BaseV25=renderMissionAgentInboxV25/.test(t644), 'released Inbox renderer is captured once for fallback and generic rows');
expect(/MISSION_PHASE1_INBOX_V25=original\.filter/.test(t644) && /finally\{MISSION_PHASE1_INBOX_V25=original;\}/.test(t644), 'enabled projection excludes only the contract rows and restores the released array');
expect(/MISSION_T644_ZERO_EFFECTS_V25=Object\.freeze/.test(t644), 'adapter publishes a closed zero-effect contract');
['network_calls','storage_writes','message_read_writes','audit_emissions','model_calls','agent_runs','worker_runs','tool_runs','outbox_deliveries','activity_promotions','external_actions'].forEach((key) => expect(new RegExp(`${key}:0`).test(t644), `T6.44 zero effects include ${key}`));
expect(/MISSION_T644_ROUTES_V25=Object\.freeze\(\['inbox','current_bundle','historical','commit'\]\)/.test(t644), 'four accepted durable-read packet routes are closed');
expect(/missionT644CanonicalV25/.test(t644) && /crypto\.subtle\.digest\('SHA-256'/.test(t644), 'packet fingerprint uses canonical recursive SHA-256 validation');
expect(/delete copy\.packet_fingerprint/.test(t644) && /fingerprint_mismatch/.test(t644), 'fingerprint recomputation excludes only the fingerprint field and fails closed');
expect(/packet\.production_writes_enabled!==false/.test(t644) && /packet\.audit_emission_enabled!==false/.test(t644) && /packet\.model_or_agent_execution!==false/.test(t644), 'packet envelope requires exact false write, audit, and execution claims');
expect(/message\.created_at<=serverTime/.test(t644) && /missionT644ReadValidV25\(ir,recipient,inboxMessageIds,packet\.server_time\)/.test(t644) && /ir\.read_at<source\.created_at/.test(t644), 'Inbox packets enforce delivery-read-server chronology');
expect(/missionT644ReadValidV25\(read,recipient,messageIds,packet\.server_time\)/.test(t644) && /read\.read_at<readMessage\.created_at/.test(t644), 'current bundle enforces delivery-read-server chronology');
expect(/MISSION_T644_EDGES_V25=Object\.freeze/.test(t644) && /receipt\.previous_state!==cursor/.test(t644), 'Journey receipts require canonical legal actors and contiguous lifecycle edges');
expect(/message\.created_at<priorMessageTime/.test(t644) && /receiptIds\.has\(receipt\.transition_receipt_id\)/.test(t644), 'message chronology and receipt identities are unique and ordered');
expect(/receipt\.resulting_state===delivered\.state_at_delivery/.test(t644) && /receipt\.occurred_at<=delivered\.created_at/.test(t644), 'each current message is backed by a reached lifecycle receipt');
expect(/expected=priorVersion===0\?1:\(revision\?priorVersion\+1:priorVersion\)/.test(t644), 'material provenance starts at Version 1 and increments only for material revision');
expect(/material\.material_digest===priorMaterial\.material_digest/.test(t644), 'material revision requires a changed digest');
expect(/\['material','state_snapshot'\]\.indexOf\(version\.version_kind\)>=0/.test(t644) && /if\(version\.version_kind==='material'\)versions\.set/.test(t644), 'current bundle validates state snapshots while lifecycle provenance uses material versions only');
expect(/missionT644ExactV25\(version,\['version_id','handoff_id','handoff_version','version_kind','material_digest','safe_summary','created_at','immutable'\]\)/.test(t644), 'material and state-snapshot version records are closed');
expect(/attachments\.get\(id\)\.message_id!==owned\.message_id/.test(t644), 'attachment ownership is bound to its exact immutable message');
expect(/reply\.source_digest===source\.content_digest/.test(t644) && /reply\.project_id===handoff\.project_id/.test(t644), 'reply context is bound to source digest and Handoff project');
expect(/health\.latest_transition_receipt_id!==latest\.transition_receipt_id/.test(t644) && /health\.latest_commit_id!==latest\.commit_id/.test(t644), 'commit health is bound to the latest canonical receipt');
expect(/controller\.cache\.set\(missionT644CacheKeyV25/.test(t644) && /MISSION_T644_CONTROLLER_V25\.recipient/.test(t644), 'verified cache is current-session and recipient-keyed');
expect(/cached\.data\.recipient_principal_id===controller\.recipient/.test(t644), 'cache fallback revalidates recipient scope');
['loading','verified','unavailable','unauthorized','conflict','legacy_local'].forEach((state) => expect(t644.includes(`${state}:[`), `T6.44 UI state map includes ${state}`));
expect(/stale:cached\?\[/.test(t644), 'T6.44 UI state map includes cache-aware stale');
expect(/controller\.ui_state='loading'/.test(t644) && /requestToken/.test(t644), 'state controller exposes loading and rejects superseded asynchronous reads');
expect(/missionT644StateMarkupV25\(controller\.ui_state,controller\.cached\)/.test(t644), 'Inbox visibly maps controller state and cache provenance without replacing its host');
expect(/stale:cached\?\['Last verified fixture'/.test(t644) && /\['Verified fixture · source marked stale'/.test(t644), 'source-declared stale and cached-stale use distinct truthful copy');
expect(/controller\.cached=false/.test(t644) && /controller\.cached=!!result\.cached/.test(t644), 'controller resets and records cache provenance for each injected read');
expect(/mc-t644-message-heading/.test(t644) && /missionT644AdjacentV25/.test(t644), 'multiple immutable messages retain exact-message focus and previous-next navigation');
expect(/missionT644OpenHandoffV25\(true/.test(t644) && /Historical Handoff · Read Only/.test(t644), 'historical links resolve through a read-only packet route');
expect(/missionT644HistoricalTabsV25\(result\.projection\)/.test(t644) && !/missionT644TabsV25\(projection,true,Number\(version\)\)/.test(t644), 'historical modal consumes the validated historical packet instead of current projection');
expect(/missionT644ExactV25\(data,\['recipient_principal_id','handoff_id','handoff_version','read_only','version','messages','attachments'\]\)/.test(t644), 'historical packet data is closed');
expect(/route==='historical'&&\(!data\|\|!missionT644IdV25\(data\.recipient_principal_id,'prn_'\)\)/.test(t644), 'historical route requires a canonical recipient principal identity');
expect(/missionT644AttachmentValidV25\(ha,data\.handoff_id,historicalIds\)/.test(t644) && /historicalOwners\.get\(id\)!==historicalMessage\.message_id/.test(t644), 'historical attachments enforce closed shape, uniqueness, ownership, and completeness');
expect(/attachment\.attachment_type==='handoff_review'/.test(t644) && /attachment\.immutable===true/.test(t644), 'attachments require typed immutable handoff-review evidence');
expect(/!historicalListed\.has\(ha\.attachment_id\)/.test(t644) && /!listedAttachmentIds\.has\(attachment\.attachment_id\)/.test(t644), 'current and historical routes reject orphan attachment records not listed by the owner message');
expect(/missionT644ExactV25\(handoff,\['handoff_id','project_id','lifecycle_state','handoff_version','material_ref','latest_transition_receipt_id','latest_message_id','row_version','etag','updated_at','privacy_class','redaction_class','retention_class'\]\)/.test(t644), 'canonical Handoff record is closed');
expect(/missionT644ExactV25\(read,\['message_read_id','message_id','recipient_principal_id','read_state','read_at'\]\)/.test(t644) && /read\.read_state==='read'/.test(t644), 'message-read projection is closed and state constrained');
expect(/missionT644ExactV25\(data,\['handoff_id','commit_id','commit_state','readback_digest','verified_at'\]\)/.test(t644), 'standalone commit packet data is closed');
expect(/missionT644ExactV25\(data,\['recipient_principal_id','handoff','versions','messages','reads','attachments','reply_contexts','receipts','commit_health'\]\)/.test(t644), 'current bundle outer data is closed');
expect(/attachment\.handoff_version!==ownerVersions\.get\(attachment\.message_id\)/.test(t644), 'current attachment version must equal its owning message version');
expect(/missionT644OpenHandoffV25\(false/.test(t644) && /Current verified fixture handoff/.test(t644), 'current links resolve the latest verified fixture bundle');
expect(/missionT644TabsV25\(projection,false,projection\.handoff\.handoff_version\)/.test(t644) && !/missionT644TabsV25\(projection,true,projection\.handoff\.handoff_version\)/.test(t644), 'current handoff renders current labeling instead of historical read-only labeling');
expect(/missionT644JourneyMarkupV25/.test(t644) && /missionT644HistoryMarkupV25/.test(t644) && />Journey<\/button>/.test(t644) && />History<\/button>/.test(t644), 'Review Journey History tabs render from normalized receipts');
expect(/controller\.scrollTop/.test(t644) && /outerLauncher/.test(t644) && /focus\(\{preventScroll:true\}\)/.test(t644), 'focus and scroll view model survive list, modal, and source return paths');
expect(/missionT644ReplyV25/.test(t644) && /Verified injected context · no send, model call, write, or execution/.test(t644), 'Mission Command reply maps safe context with truthful zero-effect copy');
expect(/input\.readOnly=true/.test(t644) && /continueMissionT616ConversationV25/.test(t644), 'fixture reply input cannot fall through to a real send path');
expect(/company&&!company\.classList\.contains\('open'\)&&typeof toggleCompanyPanel==='function'\)toggleCompanyPanel\(\)/.test(t644), 'safe reply reveals the existing Mission Command card without creating another host');
expect(/setTimeout\(function\(\)\{input\.focus\(\{preventScroll:true\}\);\},0\)/.test(t644), 'safe reply focuses the read-only Mission Command input after the card is revealed');
expect(/packet&&missionT644ExactV25\(packet,\['ok','code','fixture_only','title'\]\)&&packet\.ok===false&&packet\.code==='legacy_local'&&packet\.fixture_only===true/.test(t644), 'fake-only legacy packet has an executable closed adapter path');
expect(/ui_state:'legacy_local',projection:Object\.freeze\(\{messages:Object\.freeze\(\[\]\),title:packet\.title,read_only:true,history_available:false\}\)/.test(t644), 'legacy projection is read-only, empty, and does not invent durable history');
expect(/MISSION_T662_BROKER_ENDPOINT_V25='https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec'/.test(t644), 'T6.62 broker endpoint is one exact immutable Apps Script deployment URL');
expect(/function missionT662RequestValidV25/.test(t644) && /inbox:\['route'\]/.test(t644) && /historical:\['route','handoff_id','handoff_version'\]/.test(t644), 'T6.62 closes all four token-free request shapes before opening');
expect(/crypto\.getRandomValues\(bytes\)/.test(t644) && /'nce_'\+Array\.prototype\.map/.test(t644), 'T6.62 creates a one-use browser-memory correlation nonce');
expect(/url\.protocol==='https:'/.test(t644) && /endsWith\('\.script\.googleusercontent\.com'\)/.test(t644), 'T6.62 accepts only HTTPS Googleusercontent iframe subdomains');
expect(/event\.source===popup\|\|event\.source===window/.test(t644) && /source\.postMessage\(\{type:'t652_broker_request'/.test(t644), 'T6.62 captures the iframe source instead of trusting the popup top window');
expect(/event\.source!==source\|\|event\.origin!==origin/.test(t644), 'T6.62 pins responses to the captured iframe source and origin');
expect(/async function missionT662ResultValidV25/.test(t644) && /await missionT644ValidatePacketV25\(value\.packet,request\.route,value\.ownership\.principal_id\)/.test(t644), 'T6.62 lexically awaits the canonical packet validator');
expect(!/missionT662ResultValidV25\([^)]*validate/.test(t644) && !/validate_packet/.test(t644), 'released T6.62 integration exposes no arbitrary packet-validator injection');
expect(/missionT644ZeroV25\(value\.effects\)/.test(t644) && /value\.ownership\.handoff_id!==\(request\.handoff_id\|\|null\)/.test(t644), 'T6.62 requires exact zero effects and ownership-coordinate parity');
expect(/MISSION_T662_ACTIVE_BROKER_V25=\{nonce:nonce,cancel:function/.test(t644) && /MISSION_T662_ACTIVE_BROKER_V25\.cancel\(\)/.test(t644), 'disable cancels and closes the active broker exchange');
expect(/if\(MISSION_T662_ACTIVE_BROKER_V25\)return Promise\.resolve\(\{ok:false,code:'broker_busy'\}\)/.test(t644), 'a second broker read fails closed before nonce generation or popup open');
expect(/async function message\(event\)\{if\(finished\)return;/.test(t644), 'late queued broker events cannot revive a finished exchange');
expect(/code:'popup_blocked'/.test(t644) && /code:'timeout'/.test(t644) && /code:'closed'/.test(t644) && /code:'response_invalid'/.test(t644), 'popup, timeout, close, and invalid-response states fail closed');
expect(/if\(!MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25\)return \{ok:false,ui_state:'feature_off'/.test(t644) && /missionT662InstallBrokerAdapterV25/.test(t644), 'T6.62 adapter installation remains unreachable while the literal master flag is false');
expect(/var MISSION_T673_CANARY_ACTIVE_V25=false/.test(t644) && /async function missionT673RunCurrentBundleCanaryV25/.test(t644), 'T6.73 exposes one explicit browser-memory-only canary entrypoint');
expect(/route:'current_bundle',handoff_id:'hof_content-plan-fixture',recipient_principal_id:'prn_a1xx_fixture'/.test(t644) && /missionT644ExactV25\(request,Object\.keys\(expected\)\)/.test(t644), 'T6.73 accepts only the exact current-bundle fixture request');
expect(/MISSION_T673_CANARY_ACTIVE_V25\|\|MISSION_T662_ACTIVE_BROKER_V25/.test(t644) && /code:'broker_busy'/.test(t644), 'T6.73 rejects duplicate or overlapping canaries before broker setup');
expect(/missionT662InstallBrokerAdapterV25\(expected\.recipient_principal_id\)/.test(t644) && /await controller\.adapter\.read\(expected\.route,Object\.freeze\(\{handoff_id:expected\.handoff_id\}\)\)/.test(t644), 'T6.73 internally installs the accepted broker and performs exactly one direct current-bundle read');
expect(/await missionT644ValidatePacketV25\(packet,expected\.route,expected\.recipient_principal_id\)/.test(t644), 'T6.73 validates the returned packet with the accepted canonical validator');
expect(!/missionT644InjectFakeAdapterV25/.test(t644.match(/async function missionT673RunCurrentBundleCanaryV25\(request\)\{[^\n]+\}/)[0]) && !/renderMissionAgentInboxV25/.test(t644.match(/async function missionT673RunCurrentBundleCanaryV25\(request\)\{[^\n]+\}/)[0]), 'T6.73 does not hydrate shared UI state, render, or write the current-session packet cache');
expect(/finally\{if\(MISSION_T662_ACTIVE_BROKER_V25\)MISSION_T662_ACTIVE_BROKER_V25\.cancel\(\);controller\.adapter=null/.test(t644) && /MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25=false;MISSION_T673_CANARY_ACTIVE_V25=false/.test(t644), 'T6.73 guarantees adapter removal, cache clearing, popup cancellation, and literal flag restoration without rendering');
expect(!/(fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage|sessionStorage|indexedDB|WebSocket|new Worker|EventSource|emitAudit|auditEvent|postMissionChatLog|saveMissionChatTurn|saveMissionChatSessionTurn)/i.test(t644), 'T6.44 helper slice adds no network, storage, provider, worker, audit, or persistent chat capability');
try {
  const brokerSource = t644.slice(t644.indexOf("var MISSION_T662_BROKER_ENDPOINT_V25="), t644.indexOf('function missionT644NormalizeBundleV25'));
  const disableSource = t644.match(/function missionT644DisableV25\(\)\{[^\n]+\}/)[0];
  const probe = `'use strict';const assert=require('assert');let listener=null,openCount=0,focusCount=0;const popup={closed:false,close(){this.closed=true;}};const window={addEventListener(type,fn){listener=fn;},removeEventListener(type,fn){if(listener===fn)listener=null;},open(){openCount++;return popup;},focus(){focusCount++;}};const crypto={getRandomValues(bytes){bytes.fill(7);return bytes;}};const setTimeout=()=>1,clearTimeout=()=>{},setInterval=()=>2,clearInterval=()=>{};var MISSION_T644_ROUTES_V25=['inbox','current_bundle','historical','commit'],MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25=false,MISSION_T644_ZERO_EFFECTS_V25={},MISSION_T644_CONTROLLER_V25={requestToken:0,adapter:{},ui_state:'x',cached:true,projection:{},packet:{},selectedMessageId:'msg_x',cache:new Map([['x',1]])};function missionT644ExactV25(v,k){return !!v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).sort().join('|')===k.slice().sort().join('|');}function missionT644IdV25(v,p){return typeof v==='string'&&v.indexOf(p)===0;}function missionT644ZeroV25(){return true;}async function missionT644ValidatePacketV25(){return {ok:true};}function renderMissionAgentInboxV25(){}${brokerSource}${disableSource}(async()=>{const first=missionT662OpenBrokerV25({route:'inbox'}),late=listener;assert.equal(openCount,1);const second=await missionT662OpenBrokerV25({route:'inbox'});assert.equal(second.code,'broker_busy');assert.equal(openCount,1);missionT644DisableV25();const stopped=await first;assert.equal(stopped.code,'cancelled');assert.equal(popup.closed,true);assert.equal(MISSION_T662_ACTIVE_BROKER_V25,null);assert.equal(MISSION_T644_CONTROLLER_V25.cache.size,0);assert.equal(focusCount,1);await late({origin:'https://x.script.googleusercontent.com',source:{postMessage(){throw new Error('late post');}},data:{type:'t652_broker_ready',source_version:MISSION_T662_BROKER_SOURCE_VERSION_V25,broker_nonce:'nce_late'}});assert.equal(openCount,1);})().catch(error=>{console.error(error);process.exit(1);});`;
  child.execFileSync(process.execPath, ['-e', probe], {stdio:'pipe'});
  expect(true, 'executable broker lifecycle rejects concurrency and contains disable/late response');
} catch (error) {
  expect(false, 'executable broker lifecycle rejects concurrency and contains disable/late response');
}
try {
  const canarySource = t644.match(/async function missionT673RunCurrentBundleCanaryV25\(request\)\{[^\n]+\}/)[0];
  const probe = `'use strict';const assert=require('assert');const untouchedProjection={id:'keep'},untouchedSelection='msg_keep';var MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25=false,MISSION_T673_CANARY_ACTIVE_V25=false,MISSION_T662_ACTIVE_BROKER_V25=null,MISSION_T644_ZERO_EFFECTS_V25=Object.freeze({network_calls:0,storage_writes:0,message_read_writes:0,audit_emissions:0,model_calls:0,agent_runs:0,worker_runs:0,tool_runs:0,outbox_deliveries:0,activity_promotions:0,external_actions:0}),MISSION_T644_CONTROLLER_V25={adapter:null,recipient:'prn_original',cache:new Map(),requestToken:0,projection:untouchedProjection,selectedMessageId:untouchedSelection,scrollTop:77};let mode='success',readCalls=0,release=null,validateCalls=0,renderCalls=0;const request={route:'current_bundle',handoff_id:'hof_content-plan-fixture',recipient_principal_id:'prn_a1xx_fixture'},data={handoff:{handoff_id:'hof_content-plan-fixture',latest_transition_receipt_id:'trc_2'},messages:[{},{}],attachments:[{}],reply_contexts:[{}],receipts:[{transition_receipt_id:'trc_1',commit_id:'cmt_1'},{transition_receipt_id:'trc_2',commit_id:'cmt_2'}],commit_health:{latest_commit_id:'cmt_2',status:'verified',readback_digest:'a'.repeat(64)}},packet={freshness_status:'fresh',data};function missionT644ExactV25(value,keys){return !!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('|')===keys.slice().sort().join('|');}function missionT662InstallBrokerAdapterV25(recipient){if(!MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25)return {ok:false,ui_state:'feature_off'};MISSION_T644_CONTROLLER_V25.recipient=recipient;MISSION_T644_CONTROLLER_V25.adapter={read:async function(){readCalls++;if(mode==='pending')await new Promise(resolve=>{release=resolve;});if(mode!=='success'&&mode!=='pending')return {ok:false,code:mode};return packet;}};return {ok:true,ui_state:'ready'};}async function missionT644ValidatePacketV25(){validateCalls++;return {ok:true};}function renderMissionAgentInboxV25(){renderCalls++;}${canarySource}(async()=>{let invalid=await missionT673RunCurrentBundleCanaryV25({route:'inbox'});assert.equal(invalid.code,'request_invalid');assert.equal(readCalls,0);let success=await missionT673RunCurrentBundleCanaryV25(request);assert.equal(success.ok,true);assert.equal(success.message_count,2);assert.equal(success.latest_receipt_matches,true);assert.equal(success.commit_readback_verified,true);assert.equal(readCalls,1);assert.equal(validateCalls,1);assert.deepEqual(success.cleanup,{master_flag_false:true,adapter_removed:true,cache_cleared:true,popup_closed:true});assert.equal(renderCalls,0);assert.strictEqual(MISSION_T644_CONTROLLER_V25.projection,untouchedProjection);assert.equal(MISSION_T644_CONTROLLER_V25.selectedMessageId,untouchedSelection);assert.equal(MISSION_T644_CONTROLLER_V25.scrollTop,77);assert.equal(MISSION_T644_CONTROLLER_V25.recipient,'prn_original');mode='popup_blocked';let failed=await missionT673RunCurrentBundleCanaryV25(request);assert.equal(failed.ok,false);assert.equal(failed.code,'popup_blocked');assert.equal(MISSION_T644_DURABLE_READ_MASTER_ENABLED_V25,false);mode='pending';let first=missionT673RunCurrentBundleCanaryV25(request);await Promise.resolve();let duplicate=await missionT673RunCurrentBundleCanaryV25(request);assert.equal(duplicate.code,'broker_busy');assert.equal(readCalls,3);release();let completed=await first;assert.equal(completed.ok,true);assert.equal(readCalls,3);assert.equal(MISSION_T673_CANARY_ACTIVE_V25,false);assert.equal(MISSION_T644_CONTROLLER_V25.adapter,null);assert.equal(MISSION_T644_CONTROLLER_V25.cache.size,0);assert.equal(renderCalls,0);assert.strictEqual(MISSION_T644_CONTROLLER_V25.projection,untouchedProjection);assert.equal(MISSION_T644_CONTROLLER_V25.selectedMessageId,untouchedSelection);})().catch(error=>{console.error(error);process.exit(1);});`;
  child.execFileSync(process.execPath, ['-e', probe], {stdio:'pipe'});
  expect(true, 'executable one-shot canary covers success, failure, duplicate protection, and guaranteed cleanup');
} catch (error) {
  expect(false, 'executable one-shot canary covers success, failure, duplicate protection, and guaranteed cleanup');
}
expect(t644End < html.indexOf('var _renderMissionAgentInboxStage4BaseV25=renderMissionAgentInboxV25'), 'Stage4 captures the completed default-off T6.44 wrapper without changing its own seam');

const t644CssStart = html.indexOf('#mc-agent-inbox .mc-t644-state');
const t644CssEnd = html.indexOf('@media(max-width:1000px)', t644CssStart);
const t644Css = html.slice(t644CssStart, t644CssEnd);
expect(t644CssStart > -1 && t644CssEnd > t644CssStart, 'T6.44 presentation CSS is confined to existing Inbox and modal hosts');
expect(!/(^|[},])\s*\.mc-t644-/m.test(t644Css), 'every T6.44 selector is host scoped');
expect(/prefers-reduced-motion:reduce/.test(t644Css), 'T6.44 state and fixture views honor reduced motion');

if (failures.length) {
  console.error(`T6.4 FAIL (${failures.length})`);
  failures.forEach((failure) => console.error(`- ${failure}`));
  process.exit(1);
}
console.log(`T6.4/T6.7 PASS (${checks}/${checks})`);
