const fs = require('fs');

const html = fs.readFileSync('money-mission-tracker-v2_5.html', 'utf8');
const failures = [];
let checks = 0;
const expect = (condition, label) => { checks += 1; if (!condition) failures.push(label); };

const recognizerSource = html.match(/function missionT64JeanContentPlannerRequestV25\(text\)\{[^\n]+\}/);
expect(recognizerSource, 'deterministic recognizer exists');
if (recognizerSource) {
  const recognizes = Function(`${recognizerSource[0]}; return missionT64JeanContentPlannerRequestV25;`)();
  expect(recognizes('Create a content plan for A1XX'), 'supported content-plan request stages');
  expect(recognizes('Draft our YouTube plan'), 'supported YouTube-plan request stages');
  expect(!recognizes('Create a sales plan for A1XX'), 'unsupported job stays inert');
  expect(!recognizes('Tell me about content planning'), 'read-only question stays inert');
  expect(!recognizes('Create a content plan for Acme Corp'), 'unsupported external target stays inert');
}

const prepare = html.match(/function prepareMissionT64JeanContentPlannerPreviewV25[\s\S]*?\n\}/);
const preview = html.match(/function openMissionT64JeanContentPlannerPreviewV25[\s\S]*?\n\}/);
const ask = html.match(/askMissionCommand=function\(\)\{[^\n]+\};/);
expect(prepare && /captain:'Jean'/.test(prepare[0]), 'Jean maps to Captain');
expect(prepare && /job:'Content Planner'/.test(prepare[0]), 'Content Planner maps to Job');
expect(prepare && /stage_state:'ready'/.test(prepare[0]), 'primary state is ready');
expect(prepare && /internal_substate:'review_prepared'/.test(prepare[0]), 'initial internal substate is review prepared');
expect(prepare && /workers:\[\],tools:\[\]/.test(prepare[0]), 'Workers and tools are empty');
expect(prepare && /title:'Prepare a Content Plan for Executive Review'/.test(prepare[0]), 'approved work title includes the exact article');
expect(prepare && /owner:'Jean · Content Captain'/.test(prepare[0]), 'owner metadata is Jean Content Captain');
expect(/Chief of Staff made routing recommendation/.test(html), 'Chief remains the recommendation author');
expect(/I prepared the Content Plan handoff from the Chief of Staff’s recommendation and sent it to Agent Inbox for your review\./.test(html), 'Executive Assistant chat announces initial pre-confirm delivery');
expect(ask && /prepareMissionT64JeanContentPlannerPreviewV25\(q\)/.test(ask[0]) && !/openMissionT64JeanContentPlannerPreviewV25\(q\)/.test(ask[0]), 'Enter prepares without opening modal');
expect(ask && />Review handoff<\/button>/.test(ask[0]) && /type="button"/.test(ask[0]), 'reply has accessible Review handoff button');
expect(prepare && !/openMissionPhase1ModalV25|MISSION_PHASE1_INBOX_V25|confirmMissionAssignmentV25/.test(prepare[0]), 'preparation does not open, confirm, or create Inbox activity');
expect(preview && /openMissionT620CurrentHandoffV25/.test(preview[0]), 'Review handoff click resolves current handoff in existing modal');
expect(/item\.stage_state='parked'/.test(html), 'Park is memory-only state');
expect(/item\.stage_state='ready';item\.internal_substate='awaiting_start_approval'/.test(html), 'confirmed Jean preview remains production ready and awaits start approval');
expect(/function missionT64DecisionFeedbackV25/.test(html) && /mcShowToastV10/.test(html), 'Park and Confirm use existing toast feedback');
expect(/Handoff parked locally/.test(html) && /Submit the request again/.test(html), 'Park adds truthful EA bubble with next action');
expect(/Handoff ready for Jean/.test(html) && />Open Agent Inbox<\/button>/.test(html), 'Confirm adds truthful EA readiness bubble with accessible Inbox control');
expect(/missionT620CreateInitialDeliveryV25\(item\)/.test(prepare && prepare[0]) && /missionT626DeliverMessageV25\(item,message\)/.test(html), 'initial Jean handoff enters Inbox as its own unread delivery before confirmation');
expect(/if\(assignment\.contract==='t6_4_jean_content_planner_local_preview'\)\{item\.unread=false;renderMissionAgentInboxV25\(\)/.test(html), 'Review acknowledges the specific Jean item');
expect(/<dt>Project<\/dt>.*<dt>Captain<\/dt>.*<dt>Job<\/dt>.*<dt>Skills<\/dt>.*<dt>Workers<\/dt>.*<dt>Tools<\/dt>.*<dt>State<\/dt>/.test(html), 'Inbox Review shows full Jean handoff contract');
expect(/Jean is not dispatched/.test(html) && /separately approved execution decision/.test(html), 'Inbox detail preserves no-dispatch next step');
expect(/item\.feedbackShown===action/.test(html), 'repeat decision feedback is deduplicated');
const park = html.match(/function parkMissionT64JeanContentPlannerPreviewV25\([^)]*\)\{[^\n]+\}/);
expect(park && park[0].indexOf('closeMissionPhase1ModalV25()') < park[0].indexOf("missionT64DecisionFeedbackV25(item,'parked')"), 'Park closes modal before toast and EA bubble');
const confirm = html.match(/function confirmMissionAssignmentV25\([^)]*\)\{[^\n]+\}/);
expect(confirm && confirm[0].indexOf('closeMissionPhase1ModalV25()') < confirm[0].indexOf("missionT64DecisionFeedbackV25(item,'confirmed')"), 'Confirm still closes modal before feedback');

const addedSurface = [prepare && prepare[0], preview && preview[0], recognizerSource && recognizerSource[0], ask && ask[0]].join('\n');
expect(!/fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage\.setItem|sessionStorage\.setItem|indexedDB|new Worker\s*\(|dispatchAgent|postToAppsScript|Today|Agency Feed|receipt/i.test(addedSurface), 'preview has zero external/runtime/persistence/promotion effects');
expect(!/data-tab=|<nav|relationship map|output card/i.test(addedSurface), 'preview adds no nav, relationship map, or output surface');

const t67Start = html.indexOf('function missionT67HandoffReviewStepsMarkupV25');
const t67End = html.indexOf('function prepareMissionT64JeanContentPlannerPreviewV25');
const t67 = html.slice(t67Start, t67End);
expect(t67Start > -1 && t67End > t67Start, 'T6.7 helpers are adjacent to T6.4');
['Mission Command', 'Chief of Staff made routing recommendation', 'Executive Assistant prepared review', '@A1XX decision', 'What needs me', 'CURRENT', 'NEXT', 'LATER', 'Safe destination', 'Additional details', 'Full original command'].forEach((token) => expect(t67.includes(token), `approved hierarchy includes ${token}`));
['A1XX', 'Chief of Staff', 'Jean', 'Content Planner', 'Content Plan'].forEach((token) => expect(t67.includes(token), `visual route includes ${token}`));
['What happened', 'What now', 'What needs me', 'What this action does', 'What next'].forEach((token) => expect(t67.includes(token), `five-question readback includes ${token}`));
expect(/mode==='inbox'\?\[\['DONE','Routing confirmed',false\],\['CURRENT · NOT CONNECTED','Agent Inbox Review',true\]/.test(t67), 'Inbox Review has state-specific stepper');
expect(/data-handoff-review-state="'\+\(inbox\?'inbox':'review'\)/.test(t67), 'only review and inbox modal states render');
expect(!/data-handoff-review-state[^\n]*(confirmed|parked)/.test(t67), 'no persistent Confirmed or Parked modal states');
expect(/aria-current="step"/.test(t67) && /aria-live="polite"/.test(t67), 'stepper and readback expose state accessibly');
expect(/id="mc-t67-revision-note" aria-invalid="false" aria-describedby="mc-t67-revision-error"/.test(t67), 'revision note has accessible validation contract');
expect(/A revision note is required/.test(t67) && /input\.focus\(\{preventScroll:true\}\)/.test(t67), 'empty revision is rejected and focused');
expect(/item\.revision_note=note/.test(t67) && /nothing was staged or dispatched/.test(t67), 'valid revision stays local and truthful');
expect(/missionPhase1EscapeV25\(item\.project\)/.test(t67) && /missionPhase1EscapeV25\(\(item\.skills\|\|\[\]\)\.join/.test(t67) && /missionPhase1EscapeV25\(item\.revision_note\|\|''\)/.test(t67), 'dynamic handoff facts are escaped');
expect(/0 calls · 0 runs · 0 writes/.test(t67) && /not dispatched/.test(t67), 'zero-effect truth is visible');
expect(t67.includes('No output exists yet. A future returned result would link to one canonical Output visible through Inbox, Library, and Agents &gt; Outputs.'), 'Inbox Review states the full no-output and canonical-location contract');
expect(!/fetch\s*\(|XMLHttpRequest|WebSocket|google\.script\.run|localStorage\.setItem|sessionStorage\.setItem|indexedDB|new Worker\s*\(|postToAppsScript|dispatchAgent|deliverySend|receipt/i.test(t67), 'T6.7 helpers contain no forbidden capability');

const cssStart = html.indexOf('#mc-phase1-modal-scoped .mc-handoff-review-shell');
const cssEnd = html.indexOf('@media(max-width:1000px)', cssStart);
const t67Css = html.slice(cssStart, cssEnd);
expect(cssStart > -1 && cssEnd > cssStart, 'T6.7 scoped CSS exists');
expect(!/(^|[},])\s*\.mc-handoff-review-/m.test(t67Css), 'every Handoff Review selector is host-scoped');
['@media(max-width:760px)', '@media(max-width:520px)', '@media(prefers-reduced-motion:reduce)', 'overflow-wrap:anywhere', 'min-width:0'].forEach((token) => expect(t67Css.includes(token), `responsive CSS includes ${token}`));
expect(/\.mc-handoff-review-hero\{text-align:left/.test(t67Css) && /\.mc-handoff-review-movement\{[^}]*justify-content:flex-start/.test(t67Css), 'EA letter and compact movement are left aligned');
expect(/\.mc-handoff-review-control:hover \.mc-handoff-review-tip/.test(t67Css) && /\.mc-handoff-review-control:focus-within \.mc-handoff-review-tip/.test(t67Css), 'hidden help appears only on hover or keyboard focus-within');
expect(!/data-open|mc-handoff-review-help/.test(t67Css), 'CSS has no sticky help selector or visible help button');
expect(/\.mc-handoff-review-visible-routing \.mc-handoff-review-stepper\{margin-top:22px;gap:12px\}/.test(t67Css), 'desktop stepper has increased route separation and internal spacing');
expect(/\.mc-handoff-review-visible-routing \.mc-handoff-review-step small\{font-size:8px\}/.test(t67Css) && /\.mc-handoff-review-visible-routing \.mc-handoff-review-step b\{font-size:11px/.test(t67Css), 'stepper tags and targets are modestly larger');
expect(/@media\(max-width:760px\)[\s\S]*\.mc-handoff-review-visible-routing \.mc-handoff-review-stepper\{margin-top:16px;gap:6px\}/.test(t67Css), 'mobile stepper spacing remains proportional');
expect(/#mc-phase1-modal-scoped \.mc-handoff-review-details \.mc-handoff-review-groups\+\.mc-handoff-review-label\{display:block;margin-top:12px\}/.test(html), 'Full original command label has modest scoped separation from preceding details');
expect(/#mc-phase1-modal-scoped \.mc-handoff-review-letter\{[^}]*text-align:left/.test(html) && /\.mc-handoff-review-letter p\+p\{margin-top:7px\}/.test(html), 'EA letter is locally scoped, left aligned, and separates sentences modestly');
expect(/#mc-phase1-modal-scoped \.mc-handoff-review-signoff\{[^}]*text-align:left[^}]*font-size:10px/.test(html), 'EA sign-off uses restrained scoped message-close styling');
expect(/id="mc-phase1-modal-scoped"/.test(html), 'existing modal host carries the scope id');

const staged = html.match(/function openMissionStagedAssignmentV25\(id\)\{[^\n]+\}/);
expect(staged && /if\(assignment\.contract==='t6_4_jean_content_planner_local_preview'\)/.test(staged[0]), 'full Inbox hierarchy is contract-linked only');
expect(staged && /openMissionPhase1ModalV25\('Ready for Handoff',item\.title,'This assignment is staged locally\. No dispatch occurred\.'/.test(staged[0]), 'generic staged fallback is preserved');
expect(/if\(!MISSION_STAGE4_MASTER_ENABLED_V25\|\|!MISSION_STAGE4_BROWSER_V25\.enabled\)/.test(html), 'Stage4 default-off wrapper is preserved');
expect(/if\(modal&&modal\.classList\.contains\('open'\)\)\{event\.preventDefault\(\);closeMissionPhase1ModalV25\(\)/.test(html), 'Escape still closes modal through existing focus-return path');

const inboxRenderer = html.match(/function renderMissionAgentInboxV25\(\)\{[\s\S]*?\n\}/);
expect(inboxRenderer && /assignment\.contract==='t6_4_jean_content_planner_local_preview'/.test(inboxRenderer[0]), 'Inbox naming branch is contract-specific');
expect(inboxRenderer && /var message=missionT616MessageV25\(item\);return '<article[^\n]+<strong>'\+missionPhase1EscapeV25\(message\.subject\)/.test(inboxRenderer[0]), 'contract Inbox row leads with the EA message subject');
expect(inboxRenderer && /mc-agent-inbox-meta"><span>From: Executive Assistant<\/span><span>1 attachment<\/span><\/div>/.test(inboxRenderer[0]), 'contract row metadata is exactly EA sender and one attachment');
expect(inboxRenderer && !/Underlying author: Chief of Staff/.test(inboxRenderer[0]), 'contract list row omits Chief provenance metadata');
expect(inboxRenderer && /item\.source\+' · '\+\(item\.title\|\|item\.label\)/.test(inboxRenderer[0]), 'generic legacy source-title output is preserved');
expect(!html.includes('Jean · Jean · Content Planner'), 'redundant Jean title is absent');
expect(!html.includes("title:'Jean · Content Planner'"), 'owner and Job are not used as work title');
expect(/openMissionT620CurrentHandoffV25/.test(html) && /openMissionPhase1ModalV25\(review\?'Handoff Review':'Current Handoff',item\.title/.test(html), 'pre-decision and current Inbox attachment resolve through the work-title modal');
expect(/Your Content Plan handoff is ready for Jean/.test(html) && /Prepare a Content Plan for Executive Review is parked locally/.test(html), 'durable EA decision wording separates confirmed readiness from parked work title');
expect(/Nothing has been confirmed, started, or dispatched\./.test(html), 'initial EA chat separates prepared review from later execution');
expect(/<dt>State<\/dt><dd>Ready for confirmation<\/dd>/.test(t67), 'visible review state is Ready for confirmation');

const provenance = t67.indexOf('Chief of Staff made routing recommendation');
const eaPrepared = t67.indexOf('Executive Assistant prepared review');
const a1xxDecision = t67.indexOf('@A1XX decision');
expect(provenance > -1 && provenance < eaPrepared && eaPrepared < a1xxDecision, 'provenance orders Chief authorship, EA presentation, and A1XX decision');
expect(t67.includes('I reviewed the Chief of Staff’s recommendation and prepared this handoff for you.'), 'EA presents the recommendation conversationally');
expect(t67.includes('Jean</span><i>→</i><span>Draft Content Plan</span><i>→</i><span>@A1XX Review'), 'compact movement is exact');
['Goes to', 'Acting as', 'Expected return', 'Comes back to'].forEach((token) => expect(t67.includes(token), `four-line summary includes ${token}`));
expect(t67.includes('>Confirm Handoff</button>') && t67.includes('>Request Changes</button>') && t67.includes('>Park</button>'), 'approved decision labels are exact');
const decisionStart = t67.indexOf('Approve the Chief of Staff’s routing recommendation?');
expect(decisionStart > -1 && t67.indexOf('>Confirm Handoff</button>', decisionStart) < t67.indexOf('mc-handoff-review-safety', decisionStart), 'permanent no-start line immediately follows decision controls');
['mc-t612-confirm-tip', 'mc-t612-changes-tip', 'mc-t612-park-tip', 'role="tooltip"', 'aria-describedby'].forEach((token) => expect(t67.includes(token), `hidden decision help includes ${token}`));
expect(!/>\?<\/button>|mc-handoff-review-help|missionT612HandoffHelpV25|data-open|aria-expanded/.test(t67), 'no visible or sticky help toggle remains');
const renderedOrder = t67.slice(t67.indexOf("return '<div class=\"mc-handoff-review-shell\""));
const visibleRoute = renderedOrder.indexOf('mc-handoff-review-visible-routing');
const route = renderedOrder.indexOf('missionT67HandoffReviewRouteMarkupV25()', visibleRoute);
const stepper = renderedOrder.indexOf('missionT67HandoffReviewStepsMarkupV25(mode)', visibleRoute);
const details = renderedOrder.indexOf("+details+'</div>'");
expect(visibleRoute > -1 && visibleRoute < route && route < stepper && stepper < details, 'visible route precedes state stepper and closed Additional details');
expect(!t67.includes('<details class="mc-handoff-review-details" open'), 'Additional details is closed by default');
['Formal contract', 'Capabilities', 'Workers', 'Tools', 'Model', 'Effects', 'Source', 'Version', 'No output exists yet'].forEach((token) => expect(t67.includes(token), `deeper details include ${token}`));
expect(/missionPhase1EscapeV25\(item\.request\)/.test(t67), 'full original command is escaped for long-copy safety');

const renderT6121 = Function(`function missionPhase1EscapeV25(value){return String(value == null ? '' : value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}${t67}; return missionT67HandoffReviewBodyV25;`)();
const fixtureItem = { title: 'Prepare a Content Plan for Executive Review', project: 'A1XX', request: '<long command>', skills: ['Audience problem', 'Hook'], revision_note: '' };
const reviewMarkup = renderT6121(fixtureItem, 'review');
const inboxMarkup = renderT6121(fixtureItem, 'inbox');
const scanLabels = ['Workers', 'Tools', 'Model', 'Effects', 'Source', 'Version'];
scanLabels.forEach((label) => {
  const token = `data-scan-row="${label}"`;
  expect(reviewMarkup.split(token).length === 2, `${label} is one distinct semantic scan row`);
});
expect(!/<dt>(Workers|Tools|Model|Effects|Source|Version)<\/dt>/.test(reviewMarkup), 'six scan labels are not grouped into definition-list facts');
expect(!/data-scan-row="(?:Workers · Tools|Model · Effects|Source · Version)"/.test(reviewMarkup), 'six scan labels are never combined');
expect(reviewMarkup.includes('data-scan-row="State"><span>State</span><strong>Ready for confirmation</strong>'), 'pre-decision presentation state is exact');
expect(inboxMarkup.includes('data-scan-row="State"><span>State</span><strong>Handoff confirmed · execution not connected</strong>'), 'Inbox Review presentation state is exact');
expect((reviewMarkup.match(/Formal contract/g) || []).length === 1 && !reviewMarkup.includes('>Routing<'), 'details keep one formal contract and do not duplicate Routing');
expect(reviewMarkup.includes('Full original command') && reviewMarkup.includes('&lt;long command&gt;') && reviewMarkup.includes('No output exists yet'), 'project details preserve escaped command and no-output truth');
const letterSentences = [
  'I reviewed the Chief of Staff’s recommendation and prepared this handoff for you.',
  'The Chief recommends sending it to Jean.',
  'Jean will act as the Content Planner to prepare a Draft Content Plan and return it to you for Executive Review.'
];
expect(reviewMarkup.includes('<div class="mc-handoff-review-letter" aria-label="Executive Assistant recommendation"><p>'), 'pre-decision recommendation uses semantic EA letter markup');
expect(letterSentences.every((sentence) => reviewMarkup.includes(`<p>${sentence}</p>`)), 'each exact EA recommendation sentence has its own block');
const letterOne = reviewMarkup.indexOf(letterSentences[0]);
const letterTwo = reviewMarkup.indexOf(letterSentences[1]);
const letterThree = reviewMarkup.indexOf(letterSentences[2]);
const controlsEnd = reviewMarkup.indexOf('Nothing will start from this decision.');
const signature = reviewMarkup.indexOf('— Your Executive Assistant');
const signatureSource = reviewMarkup.indexOf('Prepared from the Chief of Staff’s recommendation.');
const lowerRoute = reviewMarkup.indexOf('mc-handoff-review-visible-routing');
expect(letterOne < letterTwo && letterTwo < letterThree && letterThree < controlsEnd && controlsEnd < signature && signature < signatureSource && signatureSource < lowerRoute, 'letter, controls, safety, EA sign-off, and lower route render in exact order');
expect((reviewMarkup.match(/— Your Executive Assistant/g) || []).length === 1 && !inboxMarkup.includes('— Your Executive Assistant') && !inboxMarkup.includes('mc-handoff-review-letter'), 'EA sign-off and letter appear only in pre-decision review');
expect(!/Executive Assistant (recommended|approved|dispatched|executed)/i.test(reviewMarkup), 'sign-off does not transfer Chief authorship or claim approval or execution');

const t616Start = html.indexOf('var MISSION_T616_ZERO_EFFECTS_V25');
const t616End = html.indexOf('function missionPhase1UnifiedInboxV25', t616Start);
const t616 = html.slice(t616Start, t616End);
expect(t616Start > -1 && t616End > t616Start, 'T6.16 contract-local fixture helpers exist adjacent to base Inbox');
['message_id', 'conversation_id', 'source_inbox_message_id', 'attachment_ids', 'project_id', 'handoff_id', 'output_id', 'safe_summary', 'default_voice'].forEach((token) => expect(t616.includes(token), `safe fixture contract includes ${token}`));
expect(/attachment_ids:\['att_'\+latest\.message_id\.slice\(4\)\]/.test(t616) && /attachment_id:message\.attachment_ids\[0\]/.test(t616), 'each selected message owns exactly one message-specific typed attachment');
expect(/1 attachment/.test(t616) && /📎/.test(t616) && /Confirmed Content Plan Handoff/.test(t616), 'Inbox detail presents one visible confirmed handoff attachment');
expect(/From · Executive Assistant/.test(t616) && /Underlying author · Chief of Staff/.test(t616), 'EA presenter and Chief author remain distinct');
expect(/You confirmed the Chief of Staff’s recommendation\./.test(t616) && /— Your Executive Assistant/.test(t616), 'Inbox owns the confirmed EA sentence letter and exact sign-off');
expect(/Ready for Jean · waiting for approval to start/.test(t616) && /Jean has not started/.test(t616), 'message state and no-start truth are visible');
expect(/Reply in Mission Command/.test(t616) && /Open original Inbox message/.test(t616) && /Continue conversation/.test(t616), 'two-way Mission Command controls are present');
expect(/closeMissionAgentInboxV25\(false\);return openMissionT620CurrentHandoffV25\(item\.assignment\.handoff_id,launcher,true\)/.test(t616), 'paperclip closes Inbox before resolving current handoff with narrow return');
expect(/openMissionT620CurrentHandoffV25/.test(t616), 'paperclip reuses the current full Handoff V1 resolver');
expect(/missionT616RestoreInboxMessageV25\('mc-t616-attachment'\)/.test(t616), 'modal close returns to the same attachment control');
expect(/MISSION_T616_INBOX_VIEW_V25\.scrollTop/.test(t616) && /list\.scrollTop=MISSION_T616_INBOX_VIEW_V25\.scrollTop/.test(t616), 'Inbox message scroll position is restored');
expect(/MISSION_T616_CONVERSATIONS_V25\[message\.source_inbox_message_id\]/.test(t616) && /if\(prior\)return \{ok:true,created:false/.test(t616), 'contextual EA conversation is page-memory and idempotent by source message');
expect(/prior&&prior\.fingerprint!==fingerprint/.test(t616) && /conflict:true/.test(t616), 'changed safe inputs produce an explicit fingerprint conflict');
expect(/Object\.freeze\(\{workspace:'Mission Command'/.test(t616) && /captain_thread:false,permanent_agent_thread:false/.test(t616), 'safe context envelope is closed and not a Captain or permanent thread');
expect(/setMissionCommandModeV25\('chat'\)/.test(t616) && /document\.getElementById\('mission-command-thread'\)/.test(t616), 'Reply reuses the existing Mission Command card and thread');
expect(!/startMissionNewChat|setActiveMissionSession|saveMissionChat|saveMissionChatSession|postMissionChatLog|_askMissionCommandPhase1BaseV25|fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage|sessionStorage|indexedDB|WebSocket|new Worker|dispatchAgent|emitAudit|auditEvent|activityLedger/i.test(t616), 'T6.16 fixture avoids persistent chat, provider, network, worker, dispatch, and audit paths');
expect(/input\.readOnly=true/.test(t616) && /MISSION_T616_CHAT_VIEW_V25\.active\)\{continueMissionT616ConversationV25\(\)/.test(html), 'contextual fixture cannot fall through to the normal send path');
expect(/item\.unread=false;renderMissionAgentInboxV25\(\)/.test(t616), 'opening message acknowledges unread without another effect');
expect(/subject:'Your Content Plan handoff is ready for Jean'/.test(t616), 'confirmed EA message subject is exact');
expect(/<h3 id="mc-t616-message-heading" tabindex="-1">'\+missionPhase1EscapeV25\(message\.subject\)/.test(t616), 'message detail heading uses the same subject field');
expect(/missionPhase1EscapeV25\(message\.subject\)/.test(inboxRenderer && inboxRenderer[0]), 'contract Inbox row uses the message subject instead of the assignment title');
expect(/title:'Prepare a Content Plan for Executive Review'/.test(prepare && prepare[0]) && /title:'Confirmed Content Plan Handoff'/.test(t616), 'formal assignment and confirmed attachment titles remain exact and separate');
expect(/aria-live="polite"/.test(t616) && /aria-label="Open '\+missionPhase1EscapeV25\(message\.attachment_title\)\+' attachment"/.test(t616), 'message detail exposes live state and a handoff-specific accessible attachment name');
['You confirmed the Chief of Staff’s recommendation.', 'The handoff is now ready for Jean to take on as Content Planner.', 'Jean has not started. The next step is your approval to begin work.'].forEach((sentence) => expect(t616.includes(sentence), `confirmed EA message data includes ${sentence}`));
expect(/No start action is connected yet/.test(t616) && /Handoff confirmed · execution not connected/.test(t67), 'confirmed Inbox and full Handoff Review both explain execution is not connected');
expect(!/(handoff was sent|Jean was sent|Jean has started|Jean was dispatched|was added to Agent Inbox)/i.test(t616), 'confirmed message makes no premature sent, started, dispatched, or Inbox-addition claim');
expect(!/added to Agent Inbox/i.test(html) && /confirmed handoff will be ready for Jean pending separate execution approval/.test(html), 'all contract copy describes readiness instead of Inbox addition');
expect(/class="mc-t616-detail" aria-live="polite" aria-current="true"/.test(t616), 'only the selected message detail exposes aria-current');
expect(/missionT616ModalReturnV25=null/.test(html) && /if\(afterClose\)\{afterClose\(\);return;\}/.test(html), 'shared modal consumes the contract return callback exactly once');
expect(/function closeMissionT616InboxMessageV25\(\)\{var originId=MISSION_T616_INBOX_VIEW_V25\.originId/.test(t616), 'Back captures the selected row focus token before rerender');
expect(/setTimeout\(function\(\)\{var origin=originId&&document\.getElementById\(originId\)\|\|document\.getElementById\('mc-agent-inbox-close'\);if\(origin\)origin\.focus\(\{preventScroll:true\}\)/.test(t616), 'Back restores the saved row after rerender without scrolling and falls back to Inbox close');
expect(/if\(MISSION_T616_INBOX_VIEW_V25\.originId===originId\)MISSION_T616_INBOX_VIEW_V25\.originId='';/.test(t616), 'row focus token is consumed only when it still matches');
expect(/MISSION_T616_INBOX_VIEW_V25\.outerLauncher=missionPhase1LastFocusV25/.test(t616), 'opening contract detail captures the ordinary outer Inbox launcher');
expect(/var outer=MISSION_T616_INBOX_VIEW_V25\.outerLauncher\|\|missionPhase1LastFocusV25;openMissionAgentInboxV25\(\);missionPhase1LastFocusV25=outer/.test(t616), 'contract reopen restores the outer launcher after ordinary popup open');
expect(/missionT616RestoreInboxMessageV25\('mc-t616-attachment'\)/.test(t616) && /missionT616RestoreInboxMessageV25\('mc-t616-message-heading'\)/.test(t616), 'attachment close and Open original return to deterministic controls');
expect(/function closeMissionAgentInboxV25\(returnFocus\)[^\n]+missionPhase1LastFocusV25\.focus/.test(html), 'Inbox X and Escape retain the generic outer-launcher focus path');

const t616CssStart = html.indexOf('.mc-agent-inbox .mc-t616-detail');
const t616CssEnd = html.indexOf('.mc-phase1-modal-backdrop', t616CssStart);
const t616Css = html.slice(t616CssStart, t616CssEnd);
expect(t616CssStart > -1 && t616CssEnd > t616CssStart, 'T6.16 CSS is scoped to the existing Inbox host');
expect(!/(^|[},])\s*\.mc-t616-/m.test(t616Css), 'every T6.16 selector is Inbox-host scoped');
['overflow-wrap:anywhere', 'min-width:0', '@media(max-width:760px),(min-resolution:1.45dppx)', '@media(prefers-reduced-motion:reduce)', 'flex-wrap:wrap'].forEach((token) => expect(t616Css.includes(token), `T6.16 responsive CSS includes ${token}`));
expect(/button:focus-visible/.test(t616Css) && /outline:2px solid/.test(t616Css), 'T6.16 controls retain visible keyboard focus');
expect(/\.mc-t626-message-nav button,.mc-agent-inbox \.mc-t616-actions button\{appearance:none;border:0;border-bottom:1px/.test(t616Css), 'message navigation and actions use low-chrome text-link controls');
expect(!/\.mc-t616-actions button:first-child/.test(t616Css) && !/\.mc-t616-actions button\{width:100%/.test(t616Css), 'message footer does not restore bulky full-width action buttons');

const t620Start = html.indexOf('var MISSION_T620_HANDOFFS_V25');
const t620End = html.indexOf('function missionT616ContractItemV25', t620Start);
const t620 = html.slice(t620Start, t620End);
expect(t620Start > -1 && t620End > t620Start, 'T6.21 canonical handoff registry is adjacent to the contract branch');
expect(/MISSION_T620_HANDOFFS_V25=\{\}/.test(t620) && /MISSION_T620_ACTIONS_V25=\{\}/.test(t620), 'handoffs and actions use isolated page-memory registries');
expect(/handoff_id:'hof_content-plan-'\+stamp/.test(html) && /handoff_version:1/.test(html) && /lifecycle_state:'review_prepared'/.test(html), 'preparation allocates one stable versioned handoff');
expect(/missionT620CreateInitialDeliveryV25\(item\)/.test(html), 'initial Inbox delivery occurs while review is prepared');
expect(/I prepared a Content Plan handoff for your review/.test(t620) && /Content Plan Handoff Review/.test(t620), 'initial message and attachment describe pre-confirm review truth');
expect(/Ready for your routing decision/.test(t620) && /unread:unread!==false/.test(t620), 'initial delivery is unread and waiting for the routing decision');
expect(/missionT620CurrentLinkV25/.test(t620) && /openMissionT620CurrentHandoffV25/.test(t620), 'current links resolve the latest state of the stable handoff');
expect(/missionT620HistoricalLinkV25/.test(t620) && /Historical Handoff · Read Only/.test(t620) && /HISTORICAL VERSION · READ ONLY/.test(t620), 'historical version links render an explicitly read-only snapshot');
expect(/View Version/.test(html) && /openMissionT620HistoricalHandoffV25/.test(html), 'current Handoff Review exposes its historical version link in Additional details');
expect(/View current handoff/.test(t620), 'historical view provides a safe path to the latest handoff state');
expect(/handoff\.lifecycle_state!==expectedState\|\|handoff\.handoff_version!==expectedVersion/.test(t620), 'decision guard checks expected state and version');
expect(/stale_action_conflict/.test(t620) && /duplicate_action_conflict/.test(t620), 'stale tabs and conflicting duplicate actions fail closed');
expect(/prior\.result==='stale'/.test(t620), 'reopening a previously rejected stale action remains rejected');
expect(/created:false/.test(t620) && /result:'applied'/.test(t620), 'identical applied action replay is idempotent');
expect(/missionT626DeliverMessageV25\(item,confirmed\)/.test(html) && /MISSION_PHASE1_INBOX_V25\.unshift\(row\)/.test(t620), 'Confirm delivers a separate immutable message row');
expect(/missionT626RowForMessageV25\(item\.handoff_id,message\.message_id\)/.test(t620) && /if\(existing\)return \{created:false,row:existing\}/.test(t620), 'duplicate delivery protection is keyed by stable handoff and exact message');
expect(/handoff\.messages\.push\(missionT620ConfirmedMessageV25/.test(t620), 'Confirm appends the immutable confirmed delivery to the same handoff');
expect(/id:'inbox_'\+message\.message_id/.test(t620) && /message_id:message\.message_id,handoff_id:item\.handoff_id/.test(t620), 'Inbox rows have distinct IDs while sharing one stable handoff');
expect(/function missionT626ExactMessageV25/.test(t616) && /message\.message_id===item\.message_id/.test(t616), 'row and detail resolve the exact immutable source message');
expect(/Message '\+\(position\+1\)\+' of '\+messages\.length/.test(t616), 'detail identifies the selected message position');
expect(/openMissionT626AdjacentMessageV25/.test(t616) && t616.includes('>Previous</button>') && t616.includes('>Next</button>'), 'detail provides bounded Previous and Next message navigation');
expect(/>Current handoff<\/button>/.test(t616) && />Attached Version '\+message\.handoff_version\+'<\/button>/.test(t616) && /openMissionT626AttachedVersionV25/.test(t616), 'detail separates latest-state resolution from its attached read-only version');
expect(/mc-t626-message-tools/.test(t616) && /mc-t626-message-nav/.test(t616) && /aria-label="Message actions"/.test(t616), 'message navigation and actions form a restrained semantic footer');
expect(/row\.unread=false/.test(t616) && /item\.unread=false/.test(t616), 'opening or navigating acknowledges only the selected message row');
expect(/source_inbox_message_id:latest\.message_id/.test(t616) && /MISSION_T616_CONVERSATIONS_V25\[message\.source_inbox_message_id\]/.test(t616), 'Reply context remains bound to the exact source message');
expect(/if\(confirmed\)missionT626DeliverMessageV25\(item,confirmed\)/.test(html) && !/existing\.unread=true;existing\.state='waiting'/.test(html), 'confirmation never mutates the initial message into the confirmed message');
expect(/Legacy local handoff · earlier history unavailable/.test(html) && /Earlier actors, approvals, timestamps, messages, and versions are unavailable/.test(html), 'pre-registry T6.16 records are labeled as legacy without invented history');
expect(/missionPhase1AssignmentV25=item/.test(t620), 'old current links restore the resolved handoff as modal context');
expect(/writes:0,storage_calls:0,network_calls:0/.test(t620) && !/(fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage|sessionStorage|indexedDB|WebSocket|new Worker|emitAudit|auditEvent)/i.test(t620), 'T6.21 registry and resolver remain exact-zero and capability-free');

expect(/function missionT623TabbedBodyV25/.test(t620), 'T6.23 tabbed handoff composition is contract-local');
expect(/role="tablist" aria-label="Handoff views"/.test(t620), 'Handoff exposes one semantic tablist');
['Review', 'Journey', 'History'].forEach((label) => expect(new RegExp('>'+label+'<\\/button>').test(t620), `T6.23 ${label} tab exists`));
expect(['review-panel','journey-panel','history-panel'].every((token) => t620.includes(token)), 'T6.23 renders the three named tab panels');
expect(/aria-selected="true"[^>]+>Review/.test(t620) && /data-view="journey"[^>]+hidden/.test(t620) && /data-view="history"[^>]+hidden/.test(t620), 'Review is default and secondary panels start hidden');
expect(/function missionT623OpenTabV25/.test(t620) && /\['review','journey','history'\]\.indexOf\(view\)<0/.test(t620), 'tab navigation rejects unknown views');
expect(/panel\.hidden=panel\.getAttribute\('data-view'\)!==view/.test(t620) && /target\.focus\(\{preventScroll:true\}\)/.test(t620), 'tab navigation changes presentation and transfers focus');
expect(/System-controlled roadmap/.test(t620) && /These are not checkboxes/.test(t620), 'Journey is explicitly system-controlled');
expect(/Chief recommendation prepared/.test(t620) && /Handoff delivered to Agent Inbox/.test(t620) && /A1XX confirmed routing/.test(t620), 'Journey contains the completed preparation and routing stages');
expect(/Approve Jean to begin/.test(t620) && /Verify dispatch/.test(t620) && /Draft Content Plan returned/.test(t620) && /Executive Review/.test(t620), 'Journey contains current and later fulfillment stages');
expect(/state==='awaiting_start_approval'\?'current':'later'/.test(t620), 'Journey derives its current start-approval stage from lifecycle state');
expect(/state==='parked'/.test(t620) && /Handoff parked · nothing is running/.test(t620), 'Journey has a truthful parked state');
expect(/local_session_at:new Date\(\)\.toISOString\(\)/.test(t620), 'History records explicit local-session timestamps');
expect(/receipt:'local-session-only'/.test(t620) && /not authenticated or durable production audit records/.test(t620), 'History denies authenticated and durable audit status');
expect(/material_version_created/.test(t620) && /review_prepared/.test(t620) && /inbox_delivered/.test(t620), 'initial history captures material version, preparation, and Inbox delivery');
expect(/routing_confirmed/.test(t620) && /Confirmed routing recommendation/.test(t620), 'Confirm appends a routing history breadcrumb');
expect(/missionT623AppendHistoryV25\(handoff,'parked'/.test(t620), 'Park appends a local history breadcrumb');
expect(/IDs and evidence/.test(t620) && /Effects 0 calls · 0 runs · 0 writes/.test(t620), 'History keeps identifiers and effects behind progressive disclosure');
expect(/body=missionT623TabbedBodyV25\(item,body,handoff\.handoff_version\)/.test(t620), 'current links open the tabbed canonical handoff');
expect(/missionT623TabbedBodyV25\(handoff\.item,missionT620HistoricalBodyV25/.test(t620), 'historical versions keep the same navigation around a read-only Review');
expect(/HISTORICAL VERSION · READ ONLY/.test(t620) && /It cannot be approved, changed, or made current/.test(t620), 'historical Review remains read-only');
expect(!/(fetch\s*\(|XMLHttpRequest|google\.script\.run|localStorage|sessionStorage|indexedDB|WebSocket|new Worker|emitAudit|auditEvent)/i.test(t620), 'T6.23 adds no persistence, provider, worker, or audit capability');

const t623CssStart = html.indexOf('#mc-phase1-modal-scoped .mc-t623-tabs-shell');
const t623CssEnd = html.indexOf('@media(max-width:1000px)', t623CssStart);
const t623Css = html.slice(t623CssStart, t623CssEnd);
expect(t623CssStart > -1 && t623CssEnd > t623CssStart, 'T6.23 CSS is confined to the existing modal host');
expect(!/(^|[},])\s*\.mc-t623-/m.test(t623Css), 'every T6.23 selector is host scoped');
expect(/@media\(max-width:760px\)/.test(t623Css) && /grid-template-columns:1fr/.test(t623Css), 'T6.23 stacks Journey and History at narrow widths');
expect(/prefers-reduced-motion:reduce/.test(t623Css) && /focus-visible/.test(t623Css) && /overflow-x:auto/.test(t623Css), 'T6.23 preserves reduced motion, keyboard focus, and tab overflow safeguards');

if (failures.length) {
  console.error(`T6.4 FAIL (${failures.length})`);
  failures.forEach((failure) => console.error(`- ${failure}`));
  process.exit(1);
}
console.log(`T6.4/T6.7 PASS (${checks}/${checks})`);
